### ISSUE TITLE
 oci_database_db_home  "Maximum wait time has been exceeded."

### ISSUE THREAD

**Issue by ladak44** [oracle/oci-ansible-collection#100]
## Issue Report

**Describe the issue**

I'm using oci_database_db_home module to apply a patch on database homes in my environment. This operation on
ExaCS 4 NODES takes about 90 mins. After 60 mins I receive an exception: "Maximum wait time has been exceeded."
[error_ansible.txt](https://github.com/oracle/oci-ansible-collection/files/6973854/error_ansible.txt)

**Expected behavior**

No errors. How to increase this timeout to 120min for example

**Environment**

(ENV) [a-cke-marclad@lxans001p exa]$ uname -a
Linux lxans001p 4.14.35-1844.4.5.el7uek.x86_64 #2 SMP Tue Apr 9 00:29:47 PDT 2019 x86_64 x86_64 x86_64 GNU/Linux

* Ansible version:

    insert output of `ansible --version` here

(ENV) [a-cke-marclad@lxans001p exa]$ ansible --version
ansible 2.10.4
  config file = /home/statoilfuelretail.com/a-cke-marclad/oci-ansible/exa/ansible_exa.cfg
  configured module search path = ['/usr/share/ansible/collections/ansible_collections/oracle/oci/plugins/modules']
  ansible python module location = /home/ansibleuser/playbooks/exa/ENV/lib64/python3.6/site-packages/ansible
  executable location = /home/ansibleuser/playbooks/exa/ENV/bin/ansible
  python version = 3.6.8 (default, Mar  9 2021, 15:08:44) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44.0.3)]

* OCI Python SDK version:

    insert output of `python -c "import oci;print(oci.__version__)"` here

(ENV) [a-cke-marclad@lxans001p exa]$ python -c "import oci;print(oci.__version__)"
2.43.2

* OCI Ansible Modules version:

    insert output of (for oracle.oci):
`ansible-galaxy collection list`

# /home/statoilfuelretail.com/a-cke-marclad/.ansible/collections/ansible_collections
Collection Version
---------- -------

# /usr/share/ansible/collections/ansible_collections
Collection Version
---------- -------
oci.2.20   *
oracle.oci 2.12.0

**Ansible playbook to reproduce the issue**

    insert a sample playbook to reproduce the issue here(if relevant to the issue)

**Comment by sagar2938** [comment]
@ladak44 , you can increase the wait_timout by passing option **wait_timeout: 7200** to the playbook task. Please share the playbook you are running if this option doens't help you.

**Comment by ladak44** [comment]
Hello, yes your advice helps. Now it's working fine. Thanks, Marcin
