### ISSUE TITLE
v2.29.0 not available on ansible-galaxy

### ISSUE THREAD

**Issue by manojmeda** [oracle/oci-ansible-collection#103]
There is an issue with uploading the latest version of collection (v2.29.0) to ansible-galaxy. We are working on it. Meanwhile please use the below command for installing:

```
ansible-galaxy collection install git+https://github.com/oracle/oci-ansible-collection.git,v2.29.0 --force
```

**Comment by rohnigam** [comment]
This issue has been resolved.

To install the latest version from Galaxy (2.29.0), use the following command:
>ansible-galaxy collection install oracle.oci --force
