### ISSUE TITLE
Abort in install.sh forced by deprecated mktemp parameter

### ISSUE THREAD

**Issue by InuSasha** [oracle/oci-ansible-collection#107]
## Issue Report

install.sh abort with error

```
bash-5.1# ./install.sh
python3.9
Downloading installer script...
mktemp: (null): Invalid argument
```

The "-t" in mktemp is deprecated and not working in every environment.
https://linux.die.net/man/1/mktemp

Removing of "-t oci_ansible_install_tmp_XXXX" from the mktemp in install.sh solved the problem, for me.
https://github.com/oracle/oci-ansible-collection/blob/master/scripts/install.sh#L214

**Environment**

* OS version: alpine:3.14

**Comment by manojmeda** [comment]
@InuSasha We don't support alpine and haven't tested with it. But we will check and see if we can update so that it works.

**Comment by rohan033** [comment]
@InuSasha This is fixed for alpine.

**Comment by InuSasha** [comment]
@rohan033 Thanks
