### ISSUE TITLE
i receive fatal: [localhost]: FAILED! =>  error when try to scale up db_system

### ISSUE THREAD

**Issue by ladak44** [oracle/oci-ansible-collection#112]
## Issue Report

**Describe the issue**
When i try to scale up db_system i receive an error:

fatal: [localhost]: FAILED! => {"changed": false, "msg": "Updating resource failed with exception: DbSystem with ID 'ocid1.dbsystem.oc1.eu-frankfurt-1.abtheljsbrlk62xdw3tjkciqqz3vwgnap7e5oxmhp5arbrnthp3leitqvuzq' does not exist or you are not authorized to access it."}
[WARNING]: Failure using method (v2_runner_on_failed) in callback plugin (<ansible_collections.community.general.plugins.callback.mail.CallbackModule object
at 0x7fce8c1ef438>): 'in <string>' requires string as left operand, not int

This db_system exists and i can scale it up from oci cli 

**Expected behavior**

no errors

**Environment**

(ENV) [a-cke-marclad@lxans001p exa]$ uname -a
Linux lxans001p 4.14.35-1844.4.5.el7uek.x86_64 #2 SMP Tue Apr 9 00:29:47 PDT 2019 x86_64 x86_64 x86_64 GNU/Linux
(ENV) [a-cke-marclad@lxans001p exa]$

(ENV) [a-cke-marclad@lxans001p exa]$ ansible --version
ansible 2.10.4
  config file = /home/statoilfuelretail.com/a-cke-marclad/oci-ansible/exa/ansible_exa.cfg
  configured module search path = ['/usr/share/ansible/collections/ansible_collections/oracle/oci/plugins/modules']
  ansible python module location = /home/ansibleuser/playbooks/exa/ENV/lib64/python3.6/site-packages/ansible
  executable location = /home/ansibleuser/playbooks/exa/ENV/bin/ansible
  python version = 3.6.8 (default, Mar  9 2021, 15:08:44) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44.0.3)]

* OCI Python SDK version:

   (ENV) [a-cke-marclad@lxans001p exa]$ python -c "import oci;print(oci.__version__)"
2.43.2

* OCI Ansible Modules version:

(ENV) [a-cke-marclad@lxans001p exa]$ ansible-galaxy collection list

# /usr/share/ansible/collections/ansible_collections
Collection Version
---------- -------
oracle.oci 2.31.0

**Ansible playbook to reproduce the issue**

  - name: Change cpu_core_count parameter
          oci_database_db_system:
              compartment_id: ocid1.compartment.oc1..aaaaaaaalwkwvvzba76ie33bn6cvybuhq7p7ynvrbdvac426vnqmwcusml5q
              db_system_id: ocid1.dbsystem.oc1.eu-frankfurt-1.abtheljsbrlk62xdw3tjkciqqz3vwgnap7e5oxmhp5arbrnthp3leitqvuzq
              cpu_core_count: '{{cpu_count|int}}'
          register: result
          when: confirmation | bool

**Comment by ladak44** [comment]
what is more. It works fine from this command:

 oci db cloud-vm-cluster update --cloud-vm-cluster-id \
> ocid1.dbsystem.oc1.eu-frankfurt-1.abtheljsbrlk62xdw3tjkciqqz3vwgnap7e5oxmhp5arbrnthp3leitqvuzq \
> --cpu-core-count 24

**Comment by rohnigam** [comment]
Hi @ladak44 ,

Thanks for sharing the info.

- [2.31.0](https://github.com/oracle/oci-ansible-collection/releases/tag/v2.31.0) version requires a minimum version of oci python sdk to be 2.45.1 . Can you please upgrade that ?
- Once upgraded can you run your playbook in verbose mode (with -vvv) and collect and share the debugs with us, the way mentioned [here](https://github.com/oracle/oci-ansible-collection/blob/master/FAQ.md#how-to-enable-debug-mode).
- It would be great if you could share with us the complete playbook as well.

**Comment by ladak44** [comment]
Hello,
It was updated
Error the same. Details in attachement.

(ENV) [a-cke-marclad@lxans001p exa]$ pip list
Package           Version
----------------- ---------
ansible           2.10.5
ansible-base      2.10.4
arrow             1.2.0
certifi           2020.12.5
cffi              1.14.4
click             7.1.2
configparser      4.0.2
cryptography      3.3.2
Jinja2            2.11.2
jmespath          0.10.0
MarkupSafe        1.1.1
oci               2.46.0
oci-cli           3.1.0
packaging         20.8
pip               21.0.1
pycparser         2.20
pyOpenSSL         19.1.0
pyparsing         2.4.7
python-dateutil   2.8.1
pytz              2020.5
PyYAML            5.4.1
retrying          1.3.3
setuptools        39.2.0
six               1.16.0
terminaltables    3.1.0
typing-extensions 3.10.0.2



(ENV) [a-cke-marclad@lxans001p exa]$ echo $ANSIBLE_LIBRARY
/usr/share/ansible/collections/ansible_collections/oracle/oci/plugins/modules


[ansible.zip](https://github.com/oracle/oci-ansible-collection/files/7278852/ansible.zip)

**Comment by rohnigam** [comment]
Hi @ladak44 ,

Thanks for sharing the above info.

Couple of things:
- What is the region configured in your oci config file ? Shouldn't be a problem since it is working for you via CLI, but we want to check this once nevertheless.
- Can you remove the compartment id in your update play and run once ?
- You forgot to collect the debugs I had mentioned. You can check [this document here](https://github.com/oracle/oci-ansible-collection/blob/master/FAQ.md#how-to-enable-debug-mode) how to collect them.

**Comment by ladak44** [comment]
Hello,
Region is: region=eu-frankfurt-1
I run this without compartment but error was the same
Debugs in attachment.
[oci_ansible_module.log.gz](https://github.com/oracle/oci-ansible-collection/files/7283851/oci_ansible_module.log.gz)

Thanks,
Marcin

**Comment by ladak44** [comment]
What is more. When I run this in dry run mode it works fine. It's odd.

(ENV) [a-cke-marclad@lxans001p exa]$ ansible-playbook /home/statoilfuelretail.com/a-cke-marclad/oci-ansible/exa/resize_error.yml --extra-vars "cpu_count=28 confirmation=yes"

PLAY [Resize the number of cpu_core_count for ckexafra2.] ***********************************************************************************************************************************************************************************

TASK [Gathering Facts] **********************************************************************************************************************************************************************************************************************
Tuesday 05 October 2021  09:55:50 +0200 (0:00:00.016)       0:00:00.016 *******
[WARNING]: Platform linux on host localhost is using the discovered Python interpreter at /usr/bin/python, but future installation of another Python interpreter could change the meaning of that path. See
https://docs.ansible.com/ansible/2.10/reference_appendices/interpreter_discovery.html for more information.
ok: [localhost]

TASK [Print cpu_core_count parameter] *******************************************************************************************************************************************************************************************************
Tuesday 05 October 2021  09:55:51 +0200 (0:00:01.128)       0:00:01.145 *******
ok: [localhost] => {
    "msg": "28"
}

TASK [Change cpu_core_count parameter] ******************************************************************************************************************************************************************************************************
Tuesday 05 October 2021  09:55:51 +0200 (0:00:00.064)       0:00:01.210 *******
changed: [localhost]

TASK [mail] *********************************************************************************************************************************************************************************************************************************
Tuesday 05 October 2021  09:55:53 +0200 (0:00:02.368)       0:00:03.579 *******
ok: [localhost]

PLAY RECAP **********************************************************************************************************************************************************************************************************************************
localhost                  : ok=4    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

Playbook run took 0 days, 0 hours, 0 minutes, 4 seconds
Tuesday 05 October 2021  09:55:54 +0200 (0:00:00.818)       0:00:04.398 *******
===============================================================================
Change cpu_core_count parameter ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ 2.37s
Gathering Facts ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 1.13s
mail --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 0.82s
Print cpu_core_count parameter ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 0.06s

**Comment by rohnigam** [comment]
Hi @ladak44 ,

You are right, we shouldn't be seeing the issue.

In the logs however I see that requests have not been logged.
You probably did not make the first change mentioned here
https://github.com/oracle/oci-ansible-collection/blob/master/FAQ.md#how-to-enable-debug-mode

This step is really necessary while collecting debug logs.

**Comment by rohnigam** [comment]
@ladak44  Also, 

- is this a virtual machine DB system ?

- In your playbook I saw you were trying to change the cores to 28. But in the oci cli command I see, you are trying to change it to 24.

- If this is a virtual machine DB system, changing cores may not work this way. Did you try changing cores to 28 via cli as well?

- Do you have multiple profiles setup in your oci config file ?

**Comment by ladak44** [comment]
Hello,
yes, this is exadata VM cluster, so yes this VM
Yes, it works fine for 28
Yes, i tried to change to 28 using cli and it works fine
No, i have only one profile

[DEFAULT]
user=ocid1.user.oc1..aaaaaaaacqkpvkbrifnc6mbaziglnqucbcsufftlgv23zadq44eys5tk2a5a
fingerprint=**************************
key_file=/home/statoilfuelretail.com/a-cke-marclad/.oci/oci_api_key.pem
tenancy=ocid1.tenancy.oc1..aaaaaaaajrosg4wf5rvk2yx7tk7ouxq332oo474dkz2wg4yp4a7jki3vzdca
region=eu-frankfurt-1
log_requests=True

**Comment by ladak44** [comment]
oci db cloud-vm-cluster update --cloud-vm-cluster-id \
ocid1.dbsystem.oc1.eu-frankfurt-1.abtheljsbrlk62xdw3tjkciqqz3vwgnap7e5oxmhp5arbrnthp3leitqvuzq \
--cpu-core-count 28

**Comment by ladak44** [comment]
this command works fine

**Comment by rohnigam** [comment]
Hey @ladak44 ,

For a Database Cloud VM Cluster, you need to use the [oci_database_cloud_vm_cluster](https://oci-ansible-collection.readthedocs.io/en/latest/collections/oracle/oci/oci_database_vm_cluster_module.html) ansible module.

You have corresponding variables for `cloud-vm-cluster-id` and `cpu-core-count` in the module. Please check them.

**Comment by ladak44** [comment]
Hello,
ok, thanks
i try to use it but i have now:

Tuesday 05 October 2021  13:20:33 +0200 (0:00:00.065)       0:00:01.216 *******
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Getting resource failed with exception: Operation failed, use the CloudVmCluster APIs for resource ocid1.dbsystem.oc1.eu-frankfurt-1.abtheljsbrlk62xdw3tjkciqqz3vwgnap7e5oxmhp5arbrnthp3leitqvuzq."}
[WARNING]: Failure using method (v2_runner_on_failed) in callback plugin (<ansible_collections.community.general.plugins.callback.mail.CallbackModule object at 0x7f2ad3feb6d8>): 'in <string>' requires string as left operand, not int

**Comment by ladak44** [comment]
- name: Change cpu_core_count parameter
          oci_database_vm_cluster:
              compartment_id: ocid1.compartment.oc1..aaaaaaaalwkwvvzba76ie33bn6cvybuhq7p7ynvrbdvac426vnqmwcusml5q
              exadata_infrastructure_id: ocid1.cloudexadatainfrastructure.oc1.eu-frankfurt-1.abtheljsarbjxnyo7zlyat7jhzwedi5zl6kkrmqrhv5rsvwzfnbewbsohtpa    
              vm_cluster_id: ocid1.dbsystem.oc1.eu-frankfurt-1.abtheljsbrlk62xdw3tjkciqqz3vwgnap7e5oxmhp5arbrnthp3leitqvuzq
              cpu_core_count: '{{cpu_count|int}}'
          register: result
          when: confirmation | bool

**Comment by rohnigam** [comment]
Hey @ladak44 ,

I am extremely sorry, I pointed you to the wrong link.
This is the module

https://oci-ansible-collection.readthedocs.io/en/latest/collections/oracle/oci/oci_database_cloud_vm_cluster_module.html#ansible-collections-oracle-oci-oci-database-cloud-vm-cluster-module


I have corrected the link in my previous comment as well.
