### ISSUE TITLE
oci_compute_instance_facts should always return boot volume data

### ISSUE THREAD

**Issue by JeremyDarling** [oracle/oci-ansible-collection#117]
## Issue Report

The oci_compute_instance_facts module does not return boot volume details when the source is an image.

            "source_details": {
                "source_type": "image",
                "boot_volume_size_in_gbs": null,
                "image_id": "xxxxx",
                "kms_key_id": null
            },

VS:

            "source_details": {
                "source_type": "bootVolume",
                "boot_volume_id": "XXX"
            },

A clear and concise description of what the issue is.

The oci_compute_instance_facts module should always return boot volume details regardless of whether the source was an image because it still has a boot volume.  Perhaps having having boot volume information outside of source_details somewhere would be helpful.

OCI Ansible

* Ansible version: 

    2.9.19

**Comment by rohan033** [comment]
Closing this issue for now.
