### ISSUE TITLE
oracle.oci.oci_database_autonomous_database: BACKUP_FROM_TIMESTAMP not working as expected

### ISSUE THREAD

**Issue by plameniliev** [oracle/oci-ansible-collection#118]
## Issue Report

When using oracle.oci.oci_database_autonomous_database and have the source field set to 'BACKUP_FROM_TIMESTAMP' I suspect the module is confusing the clone action for an update action. Maybe because for BACKUP_FROM_TIMESTAMP we also need to set autonomous_database_id as stated in the doc.

autonomous_database_id
string
		
The OCID of the source Autonomous Database that you will clone to create a new Autonomous Database.
Required for update using state=present when environment variable OCI_USE_NAME_AS_IDENTIFIER is not set.
Required for delete using state=absent when environment variable OCI_USE_NAME_AS_IDENTIFIER is not set.
Required when source is 'BACKUP_FROM_TIMESTAMP'

aliases: id

**Expected behavior**

Following the documentation and setting these fields:

timestamp
autonomous_database_id
clone_type=FULL|METADATA
source=BACKUP_FROM_TIMESTAMP

I would expect to have a cloned DB but instead getting error message that seem to suggest I am running an update action.

**Environment**

* OS version:

OL7

Linux oci-runner-57656dbcfb-pr5db 5.4.17-2102.205.7.3.el7uek.x86_64

* Ansible version:

ansible 2.9.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/oracle/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/oracle/py36venv/lib64/python3.6/site-packages/ansible
  executable location = /home/oracle/py36venv/bin/ansible
  python version = 3.6.8 (default, Mar  9 2021, 15:08:44) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44.0.3)]

* OCI Python SDK version:

2.48.0

* OCI Ansible Modules version:

    insert output of (for oracle.oci):
usage: ansible-galaxy collection [-h] COLLECTION_ACTION ...
ansible-galaxy collection: error: argument COLLECTION_ACTION: invalid choice: 'list' (choose from 'init', 'build', 'publish', 'install')

Installed via yum/dnf ...

Installing:
 oci-ansible-collection x86_64 2.32.0-1.0.1.el7        ol7_developer      7.5 M

**Ansible playbook to reproduce the issue**

- name: Sample
  hosts: localhost
  connection: local
  tasks:
    - name: Sample
      oracle.oci.oci_database_autonomous_database:

        source: "BACKUP_FROM_TIMESTAMP"
        clone_type: "FULL"
        timestamp: "2021-10-18T16:00:00Z"
        autonomous_database_id: "ocid1.autonomousdatabase.oc1.phx.anyhqljsq5fbg5aaac7ippuo2dvinyji2z62ii7iavdyh6bougzmyzhhoaaq"

        compartment_id: "ocid1.compartment.oc1..aaaaaaaa4iyvba2hh3qo6mzsit2s3cwnn5nqntgn6xevylrv7qg3zsgfay5a"
        cpu_core_count: "1"
        display_name: "sampledb"
        admin_password: "_Password1234!"
        db_name: "sampledb"
        data_storage_size_in_tbs: "1"
        license_model: "LICENSE_INCLUDED"
        are_primary_whitelisted_ips_used: false
        db_version: "19c"
        is_auto_scaling_enabled: true
        is_dedicated: false
        private_endpoint_label: "sampledb"
        nsg_ids: ["ocid1.networksecuritygroup.oc1.phx.aaaaaaaap4vh5vt5grbg6kapnif2n2cka7rqrgwqiq2nwc6q34whf7bu5gha"]
        subnet_id: "ocid1.subnet.oc1.phx.aaaaaaaa5hlksqdmgtceiqucstv5trvwcf4kcs3bk6lprzxsftvwkn7vhf7q"

**Comment by rohan033** [comment]
We have added a new parameter `source_autonomous_database_id` in v2.34.0. Closing this issue for now.
You can reopen this later or create a new one if you still face problems.
