### ISSUE TITLE
Oci-ansible-collection v2.34.0 modules documents are not updated at ReadTheDocs

### ISSUE THREAD

**Issue by dineshsuthar786** [oracle/oci-ansible-collection#124]
Oci-ansible-collection v2.34.0 modules documents are not updated at [ReadTheDocs](https://oci-ansible-collection.readthedocs.io/en/latest/collections/oracle/oci/index.html). We are working on this issue to update the modules documents at [ReadTheDocs](https://oci-ansible-collection.readthedocs.io/en/latest/collections/oracle/oci/index.html).

Please reference the Oci-ansible-collection v2.34.0 modules documents at [docs.oracle.com](https://docs.oracle.com/en-us/iaas/tools/oci-ansible-collection/latest/index.html)

**Comment by rohan033** [comment]
Closing this issue as [Read the docs](https://oci-ansible-collection.readthedocs.io/en/latest/collections/oracle/oci/index.html) is updated with latest documentation.
