### ISSUE TITLE
install.sh fails for Python 3.10

### ISSUE THREAD

**Issue by KMouratidis** [oracle/oci-ansible-collection#129]
## Issue Report

Installing with Python 3.10 fails:

```
~$  curl -L https://raw.githubusercontent.com/oracle/oci-ansible-collection/master/scripts/install.sh | bash -s -- --verbose

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7211  100  7211    0     0  19003      0 --:--:-- --:--:-- --:--:-- 19076

python3.9
bash: line 194: python3.9: command not found
python3.8
bash: line 194: python3.8: command not found
python3.7
bash: line 194: python3.7: command not found
python3.6
bash: line 194: python3.6: command not found
ERROR: python version >=3.6 is needed to install oci-ansible-collection

~$ python --version
Python 3.10.0
```

**Expected behavior**

Python >=3.6 should include 3.10 :smile: 

**Solution?**

Edit this line?
https://github.com/oracle/oci-ansible-collection/blob/master/scripts/install.sh#L162

**Comment by rohnigam** [comment]
hey @KMouratidis 

Yes. This looks like a problem.

We'll come back on this to you !

**Comment by rohan033** [comment]
@KMouratidis You can try the workaround till then by passing your python path in the `--python-path`.

`curl -L https://raw.githubusercontent.com/oracle/oci-ansible-collection/master/scripts/install.sh | bash -s -- --verbose --python-path <your_python_path>`

**Comment by rohan033** [comment]
@KMouratidis This is fixed now.
