### ISSUE TITLE
[Feature Request] Add modules that allow searching tenancy for things

### ISSUE THREAD

**Issue by DII-jkalbright** [oracle/oci-ansible-collection#135]
There should be a way to use OCI ansible to search your tenancy for things such as compute instances, block volumes, etc.

**Comment by sagar2938** [comment]
@DII-jkalbright , can you describe more about how the search would look like? we already have facts module for each of those services.

**Comment by DII-jkalbright** [comment]
What I would like to see is the ability to search your tenancy in a more generic way much like the OCI web interface 'Search' bar does.  If I have a compute instance named MYINSTANCE01, and it has a block volume called MYINSTANCE01-VOLUME01, and then that volume has a mount point called MYINSTANCE01-VOLUME01-MOUNT, I would like to be able to search my entire tenancy for "MYINSTANCE01" and it return a list containing all of these resources.  To add to that, I would like to be able to do this without the requirement of providing a compartment ID.

Again, this would essentially function just like the web interface search feature but via OCI ansible.

**Comment by sagar2938** [comment]
@DII-jkalbright , we have oci_resource_search_resource_facts to search for resources similar to "Search" bar. You find its documentation [here](https://docs.oracle.com/en-us/iaas/tools/oci-ansible-collection/2.36.0/collections/oracle/oci/oci_resource_search_resource_facts_module.html#ansible-collections-oracle-oci-oci-resource-search-resource-facts-module)

**Comment by DII-jkalbright** [comment]
@sagar2938 Thanks.  I somehow missed that module.  I just tested it out, and it works beautifully.
