### ISSUE TITLE
 Apply Exadata OS Image Update

### ISSUE THREAD

**Issue by ladak44** [oracle/oci-ansible-collection#136]
Hello,

This is not a bug but a question.
Is it feasible to make an update of exadata image using your modules?
I can't find such options.

Thanks,
Marcin

**Comment by sagar2938** [comment]
@ladak44 , could you provide more details about what exactly you are trying to update? are you trying to update exadata infrastructure ?

**Comment by ladak44** [comment]
hello, i'd like to update Virtual Machine OS Update on Exadata node. See my screenshot. 
![exadata](https://user-images.githubusercontent.com/31509190/145826153-b2b0dca2-269f-4a43-9756-a7a659e16a2e.jpg)

**Comment by sagar2938** [comment]
@ladak44 , are you able to do this action using cli command or any other tool? if you could provide the api that is invoked when this action is triggered, that will helpful.

**Comment by ladak44** [comment]
hello, currently there is no such option, so i will close this. Thanks Marcin
