### ISSUE TITLE
[RFE] Allow resizing of loadbalancer shapes in oci collections

### ISSUE THREAD

**Issue by cgmejica** [oracle/oci-ansible-collection#147]
I would like to request adding the option to resize existing load balancer shapes via the oci collections module.  It looks like this functionality is already available via the oci sdk.

```oci lb load-balancer update-load-balancer-shape```

**Comment by bsushant-athena** [comment]
Please use https://github.com/oracle/oci-ansible-collection/blob/master/plugins/modules/oci_loadbalancer_load_balancer.py
for updation of shape.

**Comment by rohan033** [comment]
@cgmejica You can refer [shape_name parameter](https://docs.oracle.com/en-us/iaas/tools/oci-ansible-collection/2.43.0/collections/oracle/oci/oci_loadbalancer_load_balancer_module.html#parameter-shape_name)

You can find a example for `Update load_balancer` in https://docs.oracle.com/en-us/iaas/tools/oci-ansible-collection/2.43.0/collections/oracle/oci/oci_loadbalancer_load_balancer_module.html#examples.


Closing this issue. Feel free to create/reopen this issue in case you need more help.
