### ISSUE TITLE
oci_golden_gate_database_registration does not support RAC databases - session_mode param is missing

### ISSUE THREAD

**Issue by krilor** [oracle/oci-ansible-collection#150]
## Feature Request

OCI GoldenGate recently (late 2021) released support for RAC databases. For this to work using the oci-ansible-collection, we need to be able to set the session_mode parameter on oci_golden_gate_database_registration.

RAC database support ( session_mode ) was added in the [Python SDK version 2.52.1](https://github.com/oracle/oci-python-sdk/commit/ad5999ef20d122a285672f4bf97b3976ff844660#diff-b6f9622a62a05383d562a1b70386f08399c21fdd17d8698cb36abf35f149d861).

### Relevant links

* https://github.com/oracle/oci-ansible-collection/blob/master/plugins/modules/oci_golden_gate_database_registration.py

**Comment by rohan033** [comment]
@krilor Thanks to bringing this to our notice. We will check internally and get back to you.

**Comment by manojmeda** [comment]
@krilor We are working on it and will include this in the next release which is planned on 3rd March.

**Comment by krilor** [comment]
@manojmeda / @rohan033 Thanks! Much appreciated :)

**Comment by rohan033** [comment]
Hi @krilor 
We are supporting the `session_mode` parameter. You can check [this](https://docs.oracle.com/en-us/iaas/tools/oci-ansible-collection/2.45.0/collections/oracle/oci/oci_golden_gate_database_registration_module.html#parameter-session_mode) document for more details.

Closing the issue.
