### ISSUE TITLE
oci_database_database_facts returns 400 for missing dbHomeId,systemId

### ISSUE THREAD

**Issue by eddedre** [oracle/oci-ansible-collection#157]
## Issue Report

**Describe the issue**

I am trying to get a list of all databases using oci_database_database_facts with only the parameter: compartment_id and it returns the following error

'MissingParameter', 'message': 'This request is missing a required value for at least one of the following arguments: dbHomeId,systemId', 'status': 400

**Expected behavior**

I should get a list of databases

**Environment**

Ubuntu 20

* Ansible version:

ansible [core 2.12.1]
  config file = None
  configured module search path = ['/home/...../.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/dist-packages/ansible
  ansible collection location = /home/....../.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.8.10 (default, Nov 26 2021, 20:14:08) [GCC 9.3.0]
  jinja version = 2.10.1
  libyaml = True

* OCI Python SDK version:

2.53.0

* OCI Ansible Modules version:

oracle.oci        2.49.0

**Ansible playbook to reproduce the issue**

  - name: List databases
    oracle.oci.oci_database_database_facts:
      compartment_id: "oci_compartment_id"

**Comment by crp987** [comment]
Hi @eddedre, Firstly as you are using latest version of Ansible modules, you should upgrade OCI Python SDK version to 2.65.0 atleast as mentioned in the changelogs (https://github.com/oracle/oci-ansible-collection/blob/master/CHANGELOG.md#changed).

The service is expecting atleast 1 of dbHomeId or systemId param to be provide alongside compartment_id which is also clear with the documentation of this module which says "Gets a list of the databases in the specified Database Home."

You can once check with the OCI Database service team on which parameter will be required alongside compartment_id.
If you face any difficulties related to Ansible, feel free to contact.

**Comment by crp987** [comment]
Closing this issue. If you face any difficulties in future do feel free to contact
