### ISSUE TITLE
How to use the inventory plugin with private_ip instead of public_ip option?

### ISSUE THREAD

**Issue by maginus-erp** [oracle/oci-ansible-collection#17]
Can you please point me to some docs / samples on how to get the inventory plugin to generate hostnames using private_ip instead of public_ip

Thanks,

**Comment by nalsaber** [comment]
Right now it is not an option to change but you can do that in the code. Update line 160:
https://github.com/oracle/oci-ansible-collection/blob/master/plugins/inventory/oci.py#L160
"hostname_format": "public_ip",
replace it with:
"hostname_format": "private_ip",

**Comment by maginus-erp** [comment]
Thanks for your response Nabeel Al-Saber.
I read through the code and I used the ~/.oci/config profile and set this setting, that seemed to work.
May be docs can state it somewhere.
