### ISSUE TITLE
Correct module name should be updated in migration guide for oci_database_db_home_patch_history_facts

### ISSUE THREAD

**Issue by shankarsundaram** [oracle/oci-ansible-collection#176]
I noticed that the module name **oci_database_db_home_patch_history_facts**  mentioned in migration guide is incorrect. please update the correct  module name.

URL: https://github.com/oracle/oci-ansible-collection/blob/master/MigrationGuide.md

**Oldname**: oci_db_home_patch_history_entry_facts
**Newname**: oci_database_db_home_patch_history_facts 

**Correct Newname**: **oci_database_db_home_patch_history_entry_facts**

**Comment by nikhiban** [comment]
Thanks for reporting this. We will include this in our next release.

**Comment by nikhiban** [comment]
Corrected module name has been updated to migration guide
