### ISSUE TITLE
Optionally return stopped compute instances in inventory plugin results

### ISSUE THREAD

**Issue by christophercollins** [oracle/oci-ansible-collection#180]
It would be extremely helpful if the inventory plugin could return any compute instances regardless of state rather than only running ones.

The reason why this is ideal is in Ansible Controller you could bring in all instances during a dynamic inventory import and set the inventory job itself to only set instances that are imported to enabled in Controller if they are actively running.

This would allow us to have the inventory run when a job across all instances are running starts up and disable any that won't be reachable because they are currently offline.

Currently a negative side-effect of the way the inventory plugin only returns running instances is if you have the the overwrite option turned on in the inventory job, and an instance is temporarily in a stopped state, Controller will remove the stopped instance along with any host specific variables because the instance "disappears" from inventory results while its off.

**Comment by manojmeda** [comment]
@christophercollins We only return running instances so that customers need not do the filtering in every playbook. Can you elaborate a bit more on your use case. Why do you want to have the stopped instances in the inventory if you cannot run any playbooks on them anyway?

**Comment by dineshsuthar786** [comment]
@christophercollins we will close the issue if we don't hear anything by tomorrow.

**Comment by manojmeda** [comment]
@christophercollins We are closing this issue since we did not get the information requested. Please feel free to reopen or create a new ticket with the information.
