### ISSUE TITLE
GoldenGate Database Registration is Deprecated

### ISSUE THREAD

**Issue by trondstromme** [oracle/oci-ansible-collection#182]
## Issue Report

**Describe the issue**

According to the REST API reference CreateDatabaseRegistration (https://docs.oracle.com/en-us/iaas/api/#/en/goldengate/20200407/DatabaseRegistration/CreateDatabaseRegistration)  is deprecatedand replaced with Connection and ConnectionAssignment https://docs.oracle.com/en-us/iaas/api/#/en/goldengate/20200407/Connection/CreateConnection / https://docs.oracle.com/en-us/iaas/api/#/en/goldengate/20200407/ConnectionAssignment/CreateConnectionAssignment

**Expected behavior**
Ansible collection is updated to support the new API

---------- -------
oracle.oci 4.0.0
**Ansible playbook to reproduce the issue**

    insert a sample playbook to reproduce the issue here(if relevant to the issue)

**Comment by dineshsuthar786** [comment]
@trondstromme Thanks for reporting the issue. We are working on this and will add support for new APIs in upcoming releases. We will update you once we add modules for new APIs.

**Comment by trondstromme** [comment]
nice! @dineshsuthar786 that was quick! 
We'll check it out as soon as possible :)
