### ISSUE TITLE
OCI Inventory oci_database_database_facts required arguments are not enough

### ISSUE THREAD

**Issue by hanabana1** [oracle/oci-ansible-collection#202]
## Issue Report

**Describe the issue**

while fetching a list of all database information from OCI an error message appears. minimum one parameter is missing, even though they are not marked as required. 

`'This request is missing a required value for at least one of the following arguments: dbHomeId,systemId', 'operation_name': 'list_databases',`

Query only works with at least the specification of the `dbHomeId`. 

**Expected behavior**

"Fetches details about one or multiple Database resources in Oracle Cloud Infrastructure"
should get a list of all databases in the compartment (compartment_id) with only the required arguments.

Example found at: https://docs.oracle.com/en-us/iaas/tools/oci-ansible-collection/4.10.0/collections/oracle/oci/oci_database_database_facts_module.html#examples

```
- name: List databases
  oci_database_database_facts:
    # required
    compartment_id: "ocid1.compartment.oc1..xxxxxxEXAMPLExxxxxx"

    # optional
    db_home_id: "ocid1.dbhome.oc1..xxxxxxEXAMPLExxxxxx"
    system_id: "ocid1.system.oc1..xxxxxxEXAMPLExxxxxx"

```

**Environment**

* OS version:  Oracle Linux release 8.7
* Ansible version:

ansible [core 2.11.12] 
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Nov 10 2022, 12:32:59) [GCC 8.5.0 20210514 (Red Hat 8.5.0-15.0.1)]
  jinja version = 2.10.1
  libyaml = True

* OCI Python SDK version: 2.90.3
* OCI Ansible Modules version: oracle.oci 4.10.0 

**Ansible playbook to reproduce the issue**

```
---
-  name: List patches
   hosts: localhost

   tasks:
    - name: List all database infos in compartment
      oracle.oci.oci_database_database_facts:
      # required
       compartment_id: "ocid1.compartment.oc1..aXXXXXXXXXXXXXXX"
      register: result
    - name: output result
      debug:
       msg: '{{result}}'
```

**Output**
`An exception occurred during task execution. To see the full traceback, use -vvv. The error was: oci.exceptions.ServiceError: {'target_service': 'database', 'status': 400, 'code': 'MissingParameter', 'opc-request-id': 'FEF5A/2C99/0EE0', 'message': 'This request is missing a required value for at least one of the following arguments: dbHomeId,systemId', 'operation_name': 'list_databases'`

**oci-ansible-collection python script with 'list_database'**

ansible_collections/oracle/oci/plugins/modules/**oci_database_database_facts.py** at line 476 - 480

 ```
   476         return oci_common_utils.list_all_resources(
    477             self.client.list_databases,
    478             compartment_id=self.module.params.get("compartment_id"),
    479             **optional_kwargs
    480         )
```

**Comment by dineshsuthar786** [comment]
@hanabana1 We generate the documentation & examples from service specs. Service team has marked `dbHomeId,systemId` parameters as optional so does modules documentation and examples. You can check the API docs for this https://docs.oracle.com/en-us/iaas/api/#/en/database/20160918/Database/ListDatabases

To know more about this, you can check with service team.

**Comment by manojmeda** [comment]
@hanabana1 Like Dinesh mentioned, the examples are generated based on the service APIs. The service has marked the parameters (dbHomeId and systemId) as optional but has an internal validation that one of them is required. It is really difficult for us to generate examples accounting for internal validations. I am closing this issue since there is not much we can do here. I would suggest you to pass one of the parameters like mentioned in the error message.
