### ISSUE TITLE
oci_object_storage_object fails when OpenSSL FIPS is enabled

### ISSUE THREAD

**Issue by FranzGames** [oracle/oci-ansible-collection#212]
## Issue Report

oci_object_storage_object task fails when OpenSSL FIPS mode is enabled on the server. It seems that the code attempts to use MD5 hash which is disabled due to FIPS mode being enabled.

Note: Using the "oci" command-line works without issue

A clear and concise description of what the issue is.

When FIPS is enabled on the server you get the error:

fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "/usr/lib64/python3.6/site-packages/cryptography/hazmat/backends/openssl/backend.py:235: UserWarning: OpenSSL FIPS mode is enabled. Can't enable DRBG fork safety.\n  UserWarning,\nTraceback (most recent call last):\n  File \"/home/opc/.ansible/tmp/ansible-tmp-1679076544.2691188-26127-242832253068869/AnsiballZ_oci_object_storage_object.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/opc/.ansible/tmp/ansible-tmp-1679076544.2691188-26127-242832253068869/AnsiballZ_oci_object_storage_object.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/opc/.ansible/tmp/ansible-tmp-1679076544.2691188-26127-242832253068869/AnsiballZ_oci_object_storage_object.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.oracle.oci.plugins.modules.oci_object_storage_object', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_oci_object_storage_object_payload_9b3a84md/ansible_oci_object_storage_object_payload.zip/ansible_collections/oracle/oci/plugins/modules/oci_object_storage_object.py\", line 527, in <module>\n  File \"/tmp/ansible_oci_object_storage_object_payload_9b3a84md/ansible_oci_object_storage_object_payload.zip/ansible_collections/oracle/oci/plugins/modules/oci_object_storage_object.py\", line 521, in main\n  File \"/tmp/ansible_oci_object_storage_object_payload_9b3a84md/ansible_oci_object_storage_object_payload.zip/ansible_collections/oracle/oci/plugins/module_utils/oci_object_storage_custom_helpers.py\", line 506, in update\n  File \"/tmp/ansible_oci_object_storage_object_payload_9b3a84md/ansible_oci_object_storage_object_payload.zip/ansible_collections/oracle/oci/plugins/module_utils/oci_object_storage_custom_helpers.py\", line 391, in download_object\n  File \"/usr/lib/python3.6/site-packages/oci/object_storage/transfer/internal/multipart_object_assembler.py\", line 205, in calculate_md5\n    md5 = hashlib.md5()\nValueError: [digital envelope routines: EVP_DigestInit_ex] disabled for fips\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

**Environment**

Oracle Linux

* OS version:

7.9

* Ansible version:

/usr/lib64/python3.6/site-packages/cryptography/hazmat/backends/openssl/backend.py:235: UserWarning: OpenSSL FIPS mode is enabled. Can't enable DRBG fork safety.
  UserWarning,
ansible-playbook-3.6 2.9.27
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/opc/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /bin/ansible-playbook-3.6
  python version = 3.6.8 (default, Nov 18 2021, 10:07:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44.0.3)]

* OCI Python SDK version:

2.90.3

* OCI Ansible Modules version:

/usr/lib64/python3.6/site-packages/cryptography/hazmat/backends/openssl/backend.py:235: UserWarning: OpenSSL FIPS mode is enabled. Can't enable DRBG fork safety.
  UserWarning,
usage: ansible-galaxy-3.6 collection [-h] COLLECTION_ACTION ...
ansible-galaxy-3.6 collection: error: argument COLLECTION_ACTION: invalid choice: 'list' (choose from 'init', 'build', 'publish', 'install')

**Ansible playbook to reproduce the issue**

---
- name: Setup VM
  connection: local
  hosts: localhost
  collections:
    - oracle.oci

  tasks:
    - name: Grab JDK
      oci_object_storage_object:
        config_file_location: oci/config
        bucket_name: 'dev-bucket'
        namespace_name: 'oracleotmgtmdev'
        object_name: 'jdk-17.0.6.tar'
        dest: 'jdk.tar.gz'

**Comment by nikhiban** [comment]
Hi @FranzGames thanks for reporting this. We have fixed this issue in our oci-ansible-collection - [4.8.0](https://github.com/oracle/oci-ansible-collection/releases/tag/v4.8.0) . Please make sure you are using equal or higher version. If issue still persists, please validate that FIPS_mode is enabled in python environment using python-sdk - https://docs.oracle.com/en-us/iaas/tools/python/2.95.0/fips-libraries.html#verifying-the-configuration.
Also, please provide us debug logs (https://docs.oracle.com/en-us/iaas/tools/oci-ansible-collection/4.16.0/guides/logging-guide.html)

**Comment by FranzGames** [comment]
Thank you. Looks like I am using 4.10.0

$ sudo rpm -q oci-ansible-collection
oci-ansible-collection-4.10.0-1.el7.x86_64

But I need to specify the FIPS_LIBCRYPTO_PATH environment variable. Adding:

export FIPS_LIBCRYPTO_PATH=/usr/lib64/libcrypto.so.10

seems to resolve the issue.
