### ISSUE TITLE
Please add variable to allow Exadata nodes to be included in inventories

### ISSUE THREAD

**Issue by jeliker** [oracle/oci-ansible-collection#224]
We have occasion to run reports, etc. referencing Exadata nodes. Please add variable similar to `fetch_db_hosts` to also include Exadata. Perhaps `fetch_db_hosts_include_exadata` or similar (default `False`)?

https://github.com/oracle/oci-ansible-collection/blob/41d54c0b9b24780a598001629a572ec3e479ce61/plugins/inventory/oci.py#L1751

**Comment by manojmeda** [comment]
@jeliker You can achieve this using filter options (include_host_filters and exclude_host_filters) provided by OCI Ansible Inventory plugin. Please check https://docs.oracle.com/en-us/iaas/tools/oci-ansible-collection/4.24.0/inventory_plugin/index.html for more details. I feel this is a more cleaner way since supporting more flags can be confusing.

**Comment by jeliker** [comment]
Please confirm your advice. The `oci.py` has a pretty clear exclusion of Exadata nodes. Thus, only VM DB or Compute systems are discovered by the plug-in presently. I am asking for Exadata nodes to be included for common management activities such as defining local users, sudoer configuration, and so on.

**Comment by dineshsuthar786** [comment]
@jeliker We do support exadata nodes in inventory plugin using `fetch_db_hosts` flag. 

[ListDbSystems](https://docs.oracle.com/en-us/iaas/api/#/en/database/20160918/DbSystem/ListDbSystems) API has deprecated support for Exadata Cloud Service systems and the API throws an error for listing deprecated exadata nodes. So, we had added above if condition to not include the deprecated exadata nodes. Service team has added new resource model APIs for exadata cloud systems. And, we are supporting this new resource model APIs to discover exadata nodes in inventory plugin.

https://github.com/oracle/oci-ansible-collection/blob/41d54c0b9b24780a598001629a572ec3e479ce61/plugins/inventory/oci.py#LL1770C1-L1779C62

If you are using deprecated exadata db systems, you might need to convert it to new resource model. Kindly let us know if you have any query or issue regarding this.

**Comment by dineshsuthar786** [comment]
@jeliker any query or update on this? If not, let us know if we can close the ticket.

**Comment by manojmeda** [comment]
@jeliker Closing the issue since we don't support deprecated exadata db systems. Please move to new resource model to fetch them from inventory plugin.
