### ISSUE TITLE
db_servers field is not optional for OCI API

### ISSUE THREAD

**Issue by Bakhtiyar-Garashov** [oracle/oci-ansible-collection#237]
## Issue Report

Hi. Here is this document (docs/collections/oracle/oci/oci_database_vm_cluster_module.rst) the field `db_servers` is marked as an optional. 

This code example below for VM cluster creation

` name: Create vm_cluster
  oci_database_vm_cluster:
    # required
    compartment_id: "ocid1.compartment.oc1..xxxxxxEXAMPLExxxxxx"
    display_name: display_name_example
    exadata_infrastructure_id: "ocid1.exadatainfrastructure.oc1..xxxxxxEXAMPLExxxxxx"
    vm_cluster_network_id: "ocid1.vmclusternetwork.oc1..xxxxxxEXAMPLExxxxxx"
    gi_version: gi_version_example
    cpu_core_count: 56
    ssh_public_keys: [ "ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAz..." ]

    # optional
    is_sparse_diskgroup_enabled: true
    is_local_backup_enabled: true
    time_zone: time_zone_example
    db_servers: [ "db_servers_example" ]
    ocpu_count: 3.4
    memory_size_in_gbs: 56
    db_node_storage_size_in_gbs: 56
    data_storage_size_in_tbs: 3.4
    data_storage_size_in_gbs: 3.4
    license_model: LICENSE_INCLUDED
    freeform_tags: {'Department': 'Finance'}
    defined_tags: {'Operations': {'CostCenter': 'US'}}
    data_collection_options:
      # optional
      is_diagnostics_events_enabled: true
      is_health_monitoring_enabled: true
      is_incident_logs_enabled: true`

 will fail with "HTTP 500, Internal server error" if you skip `db_servers` field. It needs to be fixed.

**Comment by dineshsuthar786** [comment]
@Bakhtiyar-Garashov We generate module documentation and examples using service specs. Service team has marked `db_servers` parameter as optional, so this `db_servers` parameter was generated as optional parameter in examples. you can check the [API documentation](https://docs.oracle.com/en-us/iaas/api/#/en/database/20160918/datatypes/CreateVmClusterDetails) for the same. If you have any query/issue regarding this, you can reach out to Database service team.

**Comment by manojmeda** [comment]
@Bakhtiyar-Garashov As @dineshsuthar786 mentioned, please check with the database team on why this is marked as optional. If they fix it on their end, it should automatically be fixed in all the clients including OCI Ansible.

**Comment by Bakhtiyar-Garashov** [comment]
Sadly I don't have will and time to further track this. I will not reach out to anyone else. Thanks for response.
