### ISSUE TITLE
Add OKE enhanced support (add/remove add-ons)

### ISSUE THREAD

**Issue by Noksa** [oracle/oci-ansible-collection#256]
## Issue Report

**Describe the issue**

Currently, there is no way to do that using the collection.

**Expected behavior**

We should be able to enable/disable add-ons in enhanced OKE using the collection

**Environment**

* OS version:

* Ansible version:

    insert output of `ansible --version` here

* OCI Python SDK version:

    insert output of `python -c "import oci;print(oci.__version__)"` here

* OCI Ansible Modules version:

    insert output of (for oracle.oci):
`ansible-galaxy collection list`

**Ansible playbook to reproduce the issue**

    insert a sample playbook to reproduce the issue here(if relevant to the issue)

**Comment by dineshsuthar786** [comment]
@Noksa Can you describe more about this feature request. Also, does OCI Python SDK support this.

**Comment by Noksa** [comment]
@dineshsuthar786 
Looks like I got confused by this page: https://oci-ansible-collection.readthedocs.io/en/latest/collections/oracle/oci/index.html

It still says the latest version of the collection is `4.14.0`. Looks like this page is out of date but it is in readme file.

Sorry, I tried the actual latest (4.35.0) and found what I needed.

Thanks.
