### ISSUE TITLE
OCI Ansible Collection is missing NoSQL table freeze / unfreeze and replica creation for global tables

### ISSUE THREAD

**Issue by rtaylor-talmark** [oracle/oci-ansible-collection#271]
## Issue Report

**Describe the issue**

The OCI Ansible Collection is missing NoSQL table freeze / unfreeze actions and table replica operations (create/delete) for global tables.

**Expected behavior**

In order to make use of global NoSQL tables we need the ability to freeze / unfreeze the schema state as well as the ability to create / delete replicas.

**Comment by mikebrey** [comment]
Ansible can be used to create a table with a frozen schema.   In the table module when you create a table, you pass in a DDL string.   At the end of that string do the following:    "CREATE TABLE IF NOT EXISTS     blablablabla    WITH SCHEMA FROZEN"   However this is only first half of the puzzle.    I will reach out to Ansible folks about adding a table replica module.   Thanks for alerting us the missing behavior.

**Comment by dario-vega** [comment]
@rtaylor-talmark 

- Version 4.42.0 adds support for create/delete replicas.
- See the above instructions from @mikebrey to freeze/unfreeze.

```
[4.42.0]
Added
• Support for create/delete replicas in the NoSQL Database service
• Support for update/delete row in a table in NoSQL Database service
```
More in the documentation 
https://docs.oracle.com/en-us/iaas/tools/oci-ansible-collection/4.42.0/collections/oracle/oci/oci_nosql_replica_module.html

**Comment by dineshsuthar786** [comment]
@rtaylor-talmark We are closing this issue as all the queries are resolved. Feel free to open a new issue if you still have any queries/issues.
