### ISSUE TITLE
Wrong documentation of oci user environment variables

### ISSUE THREAD

**Issue by jainnikhil30** [oracle/oci-ansible-collection#32]
## Issue Report

All the oci* modules in the new ansible collection docs refers to oci user environment variable as `OCI_USER_OCID` instead of `OCI_USER_ID`. This was already fixed in now deprecated oci-ansible-modules via https://github.com/oracle/oci-ansible-modules/issues/97. But this fix was not ported when modules migrated into this collection. Its a 1 line fix at:

https://github.com/oracle/oci-ansible-collection/blob/master/plugins/doc_fragments/oracle.py#L35

**Environment**

* Ansible version: 2.9/2.10

* OCI Python SDK version: 2.24.1

* OCI Ansible Modules version: 2.11.0

**Comment by nalsaber** [comment]
Good catch thanks for the fix we will include it in the next release!

**Comment by ruturajmolawade** [comment]
@jainnikhil30 we have fixed this issue please check our latest release of oci ansible collection.

**Comment by jainnikhil30** [comment]
@ruturajmolawade That is great ! Thanks for the update and the fix.

But, just for my information, I wanted to understand how it works in oci-ansible-collection to fix an issue. I see that the PR #33 wasn't merged but the fix was part of a large release merge https://github.com/oracle/oci-ansible-collection/pull/38. So is it always the case that bug fixes are merged as part of a release and not via individual PR's ? I just want to get the clarity from community point of view.

**Comment by manojmeda** [comment]
@jainnikhil30 For now we take the fix, add and test it internally and include it in the release. But we will have a formal process in the future to have the PRs merged here. Thanks for raising this issue and also creating a PR for the fix. We will let you know once we have the formal process ready.
