### ISSUE TITLE
oci_compute_instance SSL: CERTIFICATE_VERIFY_FAILED certificate verify failed

### ISSUE THREAD

**Issue by zdudic** [oracle/oci-ansible-collection#34]
## Issue Report

**Describe the issue**

This error causes playbook for creating PHX compute to fail. Same playbook (with relevant variables) in IAD successfully creates compute. 

**Expected behavior**

It's expected that PHX compute is created, same as IAD compute is created. 

**Environment**

* OS version:
OL7

* Ansible version:

   ansible 2.10.3
  config file = None
  configured module search path = ['/home/zdudic/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/zdudic/workspace-zdudic/python-virtualenv/oci-2.25.1/lib/python3.6/site-packages/ansible
  executable location = /home/zdudic/workspace-zdudic/python-virtualenv/oci-2.25.1/bin/ansible
  python version = 3.6.8 (default, Nov 11 2020, 09:19:43) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44.0.3)]

* OCI Python SDK version:

  2.25.1

* OCI Ansible Modules version:

Collection Version
oracle.oci 2.11.0

**Ansible playbook to reproduce the issue**

     - name: Create SVN OCI PHX compute
       oracle.oci.oci_compute_instance:    
          config_profile_name: "PHOENIX"
          availability_domain: "{{ availability_domain_phx }}"
                    compartment_id: "{{ compartment_id }}"
          shape: "{{ shape }}"
          source_details:
             source_type: image
              image_id: "{{ image_id }}" 
          display_name: "{{ compute_name_phx }}"  
          create_vnic_details:
             hostname_label: "{{ compute_name_phx }}"   
             subnet_id: "{{ subnet_id }}"   
          metadata: {
             "ssh_authorized_keys": "ssh-rsa AAAAB3Nza...W+BK6ZSyCoWosR"
                     }
          freeform_tags: {"What": "OCI PHX, created via oci-ansible-collection"}

**Comment by nalsaber** [comment]
@zdudic We are able to create instances in PHX region. Can you provide the logs? Just run the task with -vvv. We need to check all the variables passed.

**Comment by zdudic** [comment]
Attached are -vvv logs. 

[logs.txt](https://github.com/oracle/oci-ansible-collection/files/5697509/logs.txt)

**Comment by manojmeda** [comment]
@zdudic From the logs I see that you are hitting the API endpoint iaas.us-phx-1.oraclecloud.com. It should be iaas.us-phoenix-1.oraclecloud.com. Can you please check the region value in your oci config file (~/.oci/config if you are using the default) and if you have the environment variable `OCI_REGION` set. The region value should be `us-phoenix-1` and not `us-phx-1`.

**Comment by zdudic** [comment]
With region=us-phoenix-1 the error is "msg": "Authorization failed or requested resource not found." (full details in logs.txt attachment). 
I suspect 'requested resource not found' is relevant, because in ~/.oci/config, my values for user, fingerprint, key_file and tenancy are same for all regions. Even as Phoenix as DEFAULT, and with removed "config_profile_name:", I get the same error.

**Comment by nalsaber** [comment]
This seems an authentication error. Are you able to do any other operations in the PHX region? 
Try running this sample: https://github.com/oracle/oci-ansible-collection/blob/master/samples/object_storage/get_namespace/sample.yaml

**Comment by zdudic** [comment]
Seems like auth problem but not global, only for oci_compute_instance. If I add this code to playbook's beginning, I am able to list PHX compute, but then new compute creation fails. This is internal Oracle tenancy, please let me know if you want to troubleshot outside of public github (in case you need specific internal details).   

    - name: List compute
       oracle.oci.oci_compute_instance_facts:
         config_profile_name:  PHOENIX 
         compartment_id: "{{ compartment_id }}"
       register: result
     - name: Show result
       debug:
         msg: '{{ result }}'

**Comment by zdudic** [comment]
It's resolved. I overlooked that image/subnet that have same names across regions, actually have different oci id.
