### ISSUE TITLE
OCI inventory variables

### ISSUE THREAD

**Issue by spincon** [oracle/oci-ansible-collection#35]
## Issue Report

Hello,
when we generate the inventory from your plugin, all the vars are in one key dictionnary (the key being the display name of the instance), for example:
"_meta": {
        "hostvars": {
            "opmkwsysdcp01.xxxxxxxxxxx.yyyyyyyyyyyy.oraclevcn.com": {
                "opmkwsysdcp01": {
                    "agent_config": {
                        "is_management_disabled": false,
                        "is_monitoring_disabled": false
                    },
                    "availability_config": {
                        "recovery_action": "RESTORE_INSTANCE"
                    },
                    ...

So, how can we acces those variables without knowing the display name ??

**Expected behavior**

"_meta": {
        "hostvars": {
            "opmkwsysdcp01.xxxxxxxxxxx.yyyyyyyyyyyy.oraclevcn.com": {
                    "agent_config": {
                        "is_management_disabled": false,
                        "is_monitoring_disabled": false
                    },
                    "availability_config": {
                        "recovery_action": "RESTORE_INSTANCE"
                    },
                    ...

**Environment**

* OS version:

* Ansible version:

   ansible 2.10.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/awx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/my-envs/oci-venv/lib64/python3.6/site-packages/ansible
  executable location = /opt/my-envs/oci-venv/bin/ansible
  python version = 3.6.8 (default, Nov 21 2019, 19:31:34) [GCC 8.3.1 20190507 (Red Hat 8.3.1-4)]

* OCI Python SDK version:

    2.25.1

* OCI Ansible Modules version:

Collection Version
---------- -------
oracle.oci 2.11.0

**Ansible playbook to reproduce the issue**

    insert a sample playbook to reproduce the issue here(if relevant to the issue)

**Comment by kostasns** [comment]
I've noticed same behavior between .py script and oci plugin.
We workaround with `hostvars[inventory_hostname][inventory_hostname_short]`.
However, I would prefer dictionary as displayed in the expected behavior.

**Comment by AmeyaLokre** [comment]
Hello @spincon and @kostasns , thank you for bringing this to our attention. We are working on a fix for this and will update on this Github issue when it is released.

**Comment by manojmeda** [comment]
@spincon @kostasns This issue is fixed in the latest release https://github.com/oracle/oci-ansible-collection/releases/tag/v2.14.0. Please check.
