### ISSUE TITLE
Some image files seems to be corrupted and not displaying properly for the OCI Cloud Native solution

### ISSUE THREAD

**Issue by lucassrg** [oracle/oci-ansible-collection#43]
## Issue Report

**Describe the issue**
Some images file in the repository seems to be corrupted and are not displaying properly. E.g: images for cloud native solution:
https://github.com/oracle/oci-ansible-collection/blob/master/solutions/oci-cloudnative/images/logo.png
https://github.com/oracle/oci-ansible-collection/blob/master/solutions/oci-cloudnative/images/basic/00-Free-Tier.png
https://github.com/oracle/oci-ansible-collection/blob/master/solutions/oci-cloudnative/images/basic/00-Topology.png

**Expected behavior**

I was expecting to see the diagrams and pictures rendered.

**Comment by manojmeda** [comment]
@lucassrg You can find the updated version of this solution [here](https://github.com/oracle-quickstart/oci-cloudnative). In the future we will also just link to that repo. So I would recommend you to use that.

**Comment by lucassrg** [comment]
> @lucassrg You can find the updated version of this solution [here](https://github.com/oracle-quickstart/oci-cloudnative). In the future we will also just link to that repo. So I would recommend you to use that.

Thanks for the quick response @manojmeda . I understand the goal is to point to the cloudnative quickstart repo, but current galaxy documentation is pointing directly to this repo. I submitted a PR fixing these corrupted image files.

**Comment by AmeyaLokre** [comment]
Hello @lucassrg , thank you for creating a PR and providing a fix for this issue. :)
Closing this ticket as the fix PR provided by you has been merged.
