### ISSUE TITLE
Dynamic Inventory Plugin creates blank inventory. 

### ISSUE THREAD

**Issue by zdudic** [oracle/oci-ansible-collection#45]
## Issue Report

**Describe the issue**

Dynamic Inventory Plugin creates blank inventory. 
@all:
  |--@ungrouped:

**Expected behavior**

Expected to see list of computes in the compartment. 

**Environment**

* OS version: Oracle Linux Server release 7.9

* Ansible version:

    ansible 2.10.3
  config file = /home/zd/ansible.cfg
  configured module search path = ['/home/zd/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/zd/workspace-zd/python-virtualenv/oci-2.25.1/lib/python3.6/site-packages/ansible
  executable location = /home/zd/workspace-zd/python-virtualenv/oci-2.25.1/bin/ansible
  python version = 3.6.8 (default, Nov 11 2020, 09:19:43) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44.0.3)]

* OCI Python SDK version:

 2.25.1

* OCI Ansible Modules version:

Collection Version
oracle.oci 2.11.0

**Ansible playbook to reproduce the issue**

   The inventory.oci.yml reads:

oracle.oci.oci
enable_parallel_processing: yes
compartments:
-compartment_ocid: ocid1.compartment-etc
  fetch_hosts_from_subcompartments: true

**Comment by AmeyaLokre** [comment]
Hello @zdudic , can you please share the command used for running the inventory ?

**Comment by zdudic** [comment]
Sorry, this can be closed. The resolution is having below line in yml file. 

hostname_format: "private_ip"
