### ISSUE TITLE
oci_identity_tag_default - Invalid query parameters

### ISSUE THREAD

**Issue by kasadasi** [oracle/oci-ansible-collection#48]
## Issue Report

**Describe the issue**

While trying to create tag_default to the compartments getting following error.

An exception occurred during task execution. To see the full traceback, use -vvv. The error was: oci.exceptions.ServiceError: {'status': 400, 'message': u'Invalid query parameters. Exactly one filter parameter must be set from the list {id, compartmentId, tagDefinitionId}.', 'code': u'InvalidParameter', 'opc-request-id': '0F2DD754134A4AEAA0EE308DF08254FE/E17DDF9A767A30101605CE34B05C0552/3E2F1990FD7627B52D5243224687E512'}

**Expected behavior**

The playbook has to create tag_default for the compartments and set value as given.

**Environment**

* OS version:

Oracle Linux Server release 7.9
* Ansible version:

    ansible 2.9.9
  config file = /root/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /root/.local/lib/python2.7/site-packages/ansible
  executable location = /root/bin/ansible
  python version = 2.7.5 (default, Nov 13 2020, 02:52:00) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44.0.3)]

* OCI Python SDK version:

    2.23.5

* OCI Ansible Modules version:

   oci==2.23.5
oci-cli==2.10.4

**Ansible playbook to reproduce the issue**

   - name: Create OMCS Managed tag_default for OMCS managed compartments
  delegate_to: 'localhost'
  collections:
    - oracle.oci
  when: >
    inventory_hostname is defined and
    inventory_hostname is match("^([A-Z]|[0-9]|_)*-IAM$") and
    item is defined and
    item in oci_global_managed_compartments
  vars:
    oci_tag_definition_id: |
      {{ result.tags |
      json_query ( "[?name=='MANAGED'] | [0].id" ) }}
    oci_tag_compartment_id: |
      {{ oci_compartment_facts.compartments|json_query("[?name=='" + item + "']|[0].id") }}
  oci_identity_tag_default:
    config_file_location: '{{ oci_local_homedir }}/.oci/config'
    config_profile_name: '{{ oci_tenancy }}_{{ oci_datacenter }}'
    compartment_id: '{{ oci_tag_compartment_id|trim }}'
    tag_definition_id: '{{ oci_tag_definition_id|trim }}'
    value: 'TRUE'
  loop: '{{ oci_global_managed_compartments }}'

**Comment by manojmeda** [comment]
@kasadasi can you please upgrade to the latest version of the oci ansible collection and try.

**Comment by kasadasi** [comment]
@manojmeda 

  Thanks for your quick suggestion.

Before upgrading , Would like to confirm if this issue is due to older collection modules. Because it was working well so far  without any issue and suddenly we are encountering this issue.

**Comment by manojmeda** [comment]
@kasadasi one reason could be that API has added this validation recently. In the latest version, we only pass one of the parameters to mitigate this. But let me check and confirm the root cause.

**Comment by manojmeda** [comment]
@kasadasi I don't see any change related to this either in the ansible module or the python sdk. This should be a recent validation added by the API. In the latest release of the collection (v2.14.0), we mitigate this error by passing only one parameter.

**Comment by kasadasi** [comment]
@manojmeda  Thanks. I will go for an upgrade of collection module and update this thread with the result.

**Comment by kasadasi** [comment]
@manojmeda ,

  Would like to have few more queries clarified.
      What are all the changes have been made in latest release of the collection. As we have many playbooks/role developed using collection modules we wonder what impact will happen with this change.

    If you share us  the details it would help to analyse those modules and upgrade without any impact.

**Comment by manojmeda** [comment]
@kasadasi Please check the release notes https://github.com/oracle/oci-ansible-collection/releases/tag/v2.14.0 for more information.

Note: There are some breaking changes in the data safe modules since SDK also removed support for those parameters.

**Comment by kasadasi** [comment]
@manojmeda 

   Latest ansible collections module will it support existing python sdk 2.23.5 and python 2.7.5?

**Comment by manojmeda** [comment]
@kasadasi Sorry for the delay in response. I would recommend upgrading the python sdk to the latest version as well. There are some feature in the latest collection that needs the latest version of python sdk. Our modules and python sdk are both backward compatible. So your playbooks should work the same even after upgrading.

**Comment by manojmeda** [comment]
@kasadasi Please upgrade to the latest version of collection and also oci python sdk. If you still face the issue, please feel free to reopen this issue.

**Comment by manojmeda** [comment]
@kasadasi You can check [this](https://docs.ansible.com/ansible/latest/user_guide/collections_using.html#installing-an-older-version-of-a-collection) on how to install a specific version of the collection in case you need to roll back. Also we strive not to make any breaking changes. But if you see any, please let us know and we will fix it as soon as possible on priority.
