### ISSUE TITLE
[RFE] Add compartment name to OCI Plugin facts

### ISSUE THREAD

**Issue by DII-dsward** [oracle/oci-ansible-collection#56]
It would help us out to have compartment name in the hostvars pulled from the OCI plugin. Having compartment id, doesn't help us when we need to go searching for things.

**Comment by manojmeda** [comment]
@DII-dsward I assume you are talking about the OCI Inventory plugin. We do have a facts module  (`oci_identity_compartment_facts`) which you can use to fetch the compartment information.

**Comment by DII-dsward** [comment]
This doesn’t help me when I’m pulling hostvars into tower. Not having this name in here forces me to use another playbook to look up the compartment name instead of you guys adding it to the facts already available. I challenge you without using ansible to find the name of a compartment with just the OCID. Its not feasible and Oracle Cloud customer’s should not be forced to look up OCIDs because you don’t want to provide names.

**Comment by manojmeda** [comment]
@DII-dsward I understand the pain point. My only concern is it would increase the number of API calls we make internally and also might (or not) impose more permissions on the user running the plugin. We will review and get back to you.

**Comment by manojmeda** [comment]
@DII-dsward We have added `compartment_name` to the hostvars returned by the inventory plugin in the latest release v2.20.0. Please check.
