### ISSUE TITLE
Feature Request: Support delegation_token to run Ansible Inventory in Cloud Shell

### ISSUE THREAD

**Issue by k3karthic** [oracle/oci-ansible-collection#61]
## Issue Report

The Ansible inventory plugin only supports InstancePrincipalsSecurityTokenSigner as a signer.

[https://github.com/oracle/oci-ansible-collection/blob/master/plugins/inventory/oci.py#L425](https://github.com/oracle/oci-ansible-collection/blob/master/plugins/inventory/oci.py#L425)

A clear and concise description of what the issue is.

Support creating a InstancePrincipalsDelegationTokenSigner to allow the inventory plugin to run from Cloud Shell.

**Environment**

* OS version: Linux 25add1007b94 4.14.35-2047.500.10.el7uek.x86_64 #2 SMP Wed Feb 17 19:26:51 PST 2021 x86_64 x86_64 x86_64 GNU/Linux

* Ansible version:

    ansible 2.10.7

* OCI Python SDK version:

    2.35.0

* OCI Ansible Modules version:

/usr/share/ansible/collections/ansible_collections
Collection Version
oracle.oci 2.18.0 

/usr/local/lib/python3.6/site-packages/ansible_collections
Collection                    Version
amazon.aws                    1.4.1  
ansible.netcommon             1.5.0  
ansible.posix                 1.2.0  
ansible.utils                 2.0.2  
ansible.windows               1.4.0  
arista.eos                    1.3.0  
awx.awx                       17.1.0 
azure.azcollection            1.4.0  
check_point.mgmt              2.0.0  
chocolatey.chocolatey         1.0.2  
cisco.aci                     2.0.0  
cisco.asa                     1.0.4  
cisco.intersight              1.0.12 
cisco.ios                     1.3.0  
cisco.iosxr                   1.2.1  
cisco.meraki                  2.2.1  
cisco.mso                     1.1.0  
cisco.nso                     1.0.3  
cisco.nxos                    1.4.0  
cisco.ucs                     1.6.0  
cloudscale_ch.cloud           2.1.0  
community.aws                 1.4.0  
community.azure               1.0.0  
community.crypto              1.6.0  
community.digitalocean        1.0.0  
community.docker              1.4.0  
community.fortios             1.0.0  
community.general             2.4.0  
community.google              1.0.0  
community.grafana             1.2.0  
community.hashi_vault         1.1.3  
community.hrobot              1.1.1  
community.kubernetes          1.2.0  
community.kubevirt            1.0.0  
community.libvirt             1.0.1  
community.mongodb             1.2.1  
community.mysql               1.3.0  
community.network             2.1.0  
community.okd                 1.1.0  
community.postgresql          1.2.0  
community.proxysql            1.0.0  
community.rabbitmq            1.0.3  
community.routeros            1.1.0  
community.skydive             1.0.0  
community.sops                1.0.6  
community.vmware              1.8.0  
community.windows             1.3.0  
community.zabbix              1.3.0  
containers.podman             1.4.4  
cyberark.conjur               1.1.0  
cyberark.pas                  1.0.6  
dellemc.openmanage            3.2.0  
dellemc.os10                  1.1.1  
dellemc.os6                   1.0.7  
dellemc.os9                   1.0.4  
f5networks.f5_modules         1.8.1  
fortinet.fortimanager         2.0.1  
fortinet.fortios              1.1.9  
frr.frr                       1.0.3  
gluster.gluster               1.0.1  
google.cloud                  1.0.2  
hetzner.hcloud                1.3.1  
ibm.qradar                    1.0.3  
infinidat.infinibox           1.2.4  
inspur.sm                     1.1.2  
junipernetworks.junos         1.3.0  
kubernetes.core               1.2.0  
mellanox.onyx                 1.0.0  
netapp.aws                    20.9.0 
netapp.elementsw              20.11.0
netapp.ontap                  21.3.1 
netapp_eseries.santricity     1.1.0  
netbox.netbox                 2.1.0  
ngine_io.cloudstack           2.0.0  
ngine_io.exoscale             1.0.0  
ngine_io.vultr                1.1.0  
openstack.cloud               1.3.0  
openvswitch.openvswitch       1.2.0  
ovirt.ovirt                   1.4.1  
purestorage.flasharray        1.7.0  
purestorage.flashblade        1.5.0  
sensu.sensu_go                1.9.3  
servicenow.servicenow         1.0.4  
splunk.es                     1.0.2  
t_systems_mms.icinga_director 1.16.0 
theforeman.foreman            1.5.1  
vyos.vyos                     1.1.1  
wti.remote                    1.0.1 

**Ansible playbook to reproduce the issue**

plugin: oracle.oci.oci

regions:
    - ap-hyderabad-1
    
enable_parallel_processing: yes

debug: True

**Comment by dineshsuthar786** [comment]
@k3karthic, Thanks for requesting this feature. We have released `delegation_token` based authentication for Inventory Plugin in [Release v2.21.0](https://github.com/oracle/oci-ansible-collection/releases/tag/v2.21.0). Closing the issue.
