### ISSUE TITLE
oci_object_storage_object - Deleting bucket in object storage takes huge amount  of time

### ISSUE THREAD

**Issue by kasadasi** [oracle/oci-ansible-collection#63]
Describe the issue

 When we try to delete a bucket in object storage it takes atleast 24 hours to delete 1TB data where as directly on the console it takes only 2-3 hours. 

Expected behavior

The playbook has to take same amount of time what it takes directly on the console.

Environment

OS version:
Oracle Linux Server release 7.9

Ansible version:

ansible 2.9.9
config file = /root/ansible.cfg
configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
ansible python module location = /root/.local/lib/python2.7/site-packages/ansible
executable location = /root/bin/ansible
python version = 2.7.5 (default, Nov 13 2020, 02:52:00) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44.0.3)]

OCI Python SDK version:

2.23.5

OCI Ansible Modules version:

oci==2.23.5
oci-cli==2.10.4

Ansible playbook to reproduce the issue

- name: 'Set bucket name fact'
  when:
    inventory_hostname is defined and
    inventory_hostname is search ('_decom')
  set_fact:
    bucket_name: '{{ outer_item|trim }}'
- name: 'Get the object storage namespace'
  collections:
     - oracle.oci
  delegate_to: 'localhost'
  oci_object_storage_namespace_facts:
     compartment_id: '{{ oci_config_tenancy }}'
     config_file_location: '{{ oci_local_homedir }}/.oci/config'
     config_profile_name: '{{ oci_tenancy }}_{{ oci_datacenter }}'
  register: namespace_facts
- name: 'Set namespace fact'
  when: >
     namespace_facts is defined
  set_fact:
    namespace_name: '{{ namespace_facts.namespace }}'
- name: 'Fetch details of objectstorage'
  collections:
     - oracle.oci
  when: >
    namespace_name is defined and
    namespace_name|length > 0 and
    bucket_name is defined and
    bucket_name|length > 0
  delegate_to: 'localhost'
  ignore_errors: 'true'
  oci_object_storage_bucket_facts:
     namespace_name: '{{ namespace_name }}'
     bucket_name: '{{ bucket_name }}'
     config_file_location: '{{ oci_local_homedir }}/.oci/config'
     config_profile_name: '{{ oci_tenancy }}_{{ oci_datacenter }}'
  register: bucket_results
- name: 'Fetch details of objects on {{ bucket_name }}'
  collections:
     - oracle.oci
  when: >
    namespace_name is defined and
    namespace_name|length > 0 and
    bucket_results is defined and
    bucket_name is defined and
    bucket_name|length > 0
  delegate_to: localhost
  ignore_errors: 'true'
  oci_object_storage_object_facts:
     namespace_name: '{{ namespace_name }}'
     bucket_name: '{{ bucket_name }}'
     config_file_location: '{{ oci_local_homedir }}/.oci/config'
     config_profile_name: '{{ oci_tenancy }}_{{ oci_datacenter }}'
  register: object_results
- name: 'Get bucket OCID'
  ignore_errors: 'true'
  when: >
    bucket_results is defined and
    bucket_name is defined
  set_fact:
    bucket_ocid: |
      {{ bucket_results.bukets |json_query("[?name=='" + bucket_name|trim + "']|[0].id") }}
- name: 'Bucket details'
  ignore_errors: 'true'
  when: >
    bucket_ocid is defined
  debug:
    msg: 'deleting the following bucket with all objects ....
         BUCKET-NAME: {{ bucket_results.buckets[0].name }}, NAMESPACE: {{ bucket_results.buckets[0].namespace }}, time_created: {{ bucket_results.buckets[0].time_created }}'
- name: 'Fetch list of preauthenticated_requests'
  collections:
    - oracle.oci
  delegate_to: localhost
  ignore_errors: 'true'
  oci_object_storage_preauthenticated_request_facts:
     namespace_name: '{{ namespace_name }}'
     bucket_name: '{{ bucket_name }}'
     config_file_location: '{{ oci_local_homedir }}/.oci/config'
     config_profile_name: '{{ oci_tenancy }}_{{ oci_datacenter }}'
  register: preauth_results
- name: 'Remove preauthenticated_requests of {{ bucket_name }}'
  collections:
     - oracle.oci
  when: >
    preauth_results is defined and
    preauth_results.preauthenticated_requests|length|int > 0
  delegate_to: localhost
  ignore_errors: 'true'
  oci_object_storage_preauthenticated_request:
    namespace_name: '{{ namespace_name }}'
    bucket_name: '{{ bucket_name }}'
    par_id: '{{ item.id }}'
    state: absent
    config_file_location: '{{ oci_local_homedir }}/.oci/config'
    config_profile_name: '{{ oci_tenancy }}_{{ oci_datacenter }}'
  loop: '{{ preauth_results.preauthenticated_requests }}'
  loop_control:
    label: '{{ item.name }}'
- name: 'Deleting all objects on {{ bucket_name }}'
  collections:
     - oracle.oci
  delegate_to: localhost
  ignore_errors: 'true'
  when: >
    object_results is defined and
    object_results.objects|length|int > 0
  oci_object_storage_object:
    namespace_name: '{{ namespace_name }}'
    bucket_name: '{{ bucket_name }}'
    object_name: "{{ item.name }}"
    config_file_location: '{{ oci_local_homedir }}/.oci/config'
    config_profile_name: '{{ oci_tenancy }}_{{ oci_datacenter }}'
    state: absent
  loop: '{{ object_results.objects }}'
  loop_control:
      label: '{{ item.name }}'
- name: 'Deleting bucket {{ bucket_name }}'
  collections:
     - oracle.oci
  delegate_to: localhost
  ignore_errors: 'true'
  when: >
    bucket_ocid is defined
  oci_object_storage_bucket:
     namespace_name: '{{ namespace_name }}'
     name: '{{ bucket_name }}'
     state: 'absent'
     config_file_location: '{{ oci_local_homedir }}/.oci/config'
     config_profile_name: '{{ oci_tenancy }}_{{ oci_datacenter }}'

**Comment by manojmeda** [comment]
@kasadasi Thanks for reporting the issue. We will check and get back to you.

**Comment by rohnigam** [comment]
Hi @kasadasi ,
I have the below questions :
- Is this an intermittent issue or are you consistently reproducing this ?
- How many objects do you have in your bucket ? And what size ?
- Does this also happen if you have lesser objects in the bucket ?

**Comment by kasadasi** [comment]
Please find an update below,

Is this an intermittent issue or are you consistently reproducing this ? 
we are getting consistently

How many objects do you have in your bucket ? And what size ? 
we have tried the automation for 7 TB amd 30 TB and faced the same problem

Does this also happen if you have lesser objects in the bucket ? 
yes

Thanks,
Kathirvel.S

**Comment by rohnigam** [comment]
Hi @kasadasi,

Thanks for answering the queries.

We find similar results in our local reproduction as well.

After further debugging I find that there are some differences 
between how console and how Ansible modules work and that is  
causing the playbook to take relatively more time.

There is nothing specific with respect to these object storage modules
that is wrong, however, we are checking for other options to make the
experience better.

We'll update this thread when we have more.

**Comment by kasadasi** [comment]
@rohnigam 

 Thanks for an update. Sorry for the delayed response.

 Could you please share the progress update on this.

**Comment by rohnigam** [comment]
Hi @kasadasi 

We are working on an approach to make the experience better.
We'll try to publish it this release.

**Comment by kasadasi** [comment]
Thanks for an update.

**Comment by rohnigam** [comment]
@kasadasi

You can use the below format for deleting a non-empty bucket forcefully.

```
- name: Delete bucket
  oci_object_storage_bucket:
     namespace_name: "{{ test_namespace_name }}"
     name: "{{ test_bucket_name }}"
     state: absent
     force: True                      # newly added
  register: result
```

This will also delete the objects faster than the default experience.

Please upgrade to the latest version of oci ansible collection 2.21.0 .

**Comment by kasadasi** [comment]
Thanks for the update.

 Will the Force option works for deleting objects in the bucket(oci_object_storage_object)?

We have two tasks,
First task will delete the objects in the bucket , second task will delete the bucket.

From your update what I see is Force option is enabled for deleting bucket instead of object.

**Comment by rohnigam** [comment]
@kasadasi 

The *force* option is on the bucket, and this will delete the objects contained within  
the bucket along with the bucket, just like the behaviour on the console.

**Comment by kasadasi** [comment]
So you mean , instead of deleting the objects first I should delete the buckets directly.

Am I right?

**Comment by rohnigam** [comment]
@kasadasi Yes.

**Comment by kasadasi** [comment]
Can 30TB data in the bucket can be deleted directly without deleting objects.

**Comment by rohnigam** [comment]
@kasadasi 

Here's what happens when you delete the bucket  
the way I have mentioned above (in one ansible task),   
- all the objects in the bucket will be deleted.   
   You **do not have to** call delete on each/any these objects explicitly.  
- Wouldn't matter what the size of those objects are.
- Following that, the bucket would also be deleted.

**Comment by kasadasi** [comment]
Thanks, Will test this and let you know if any queries.

**Comment by kasadasi** [comment]
Hi,
 I am getting following error when I use force: yes

TASK [oci_collection_decomm_objectstorage_modified : Deleting bucket kathir-test-bucket] ******************************************************
Monday 10 May 2021  09:41:25 +0000 (0:00:00.026)       0:00:30.311 ************
fatal: [aucuhca01_iad_decom_buckets_test]: FAILED! => {"changed": false, "module_stderr": "/usr/lib/python2.7/site-packages/oci/_vendor/httpsig_cffi/sign.py:10: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in a future release.\n  from cryptography.hazmat.backends import default_backend  # noqa: F401\nTraceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1620639685.92-15693-123366084114094/AnsiballZ_oci_object_storage_bucket.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1620639685.92-15693-123366084114094/AnsiballZ_oci_object_storage_bucket.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1620639685.92-15693-123366084114094/AnsiballZ_oci_object_storage_bucket.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.oracle.oci.plugins.modules.oci_object_storage_bucket', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python2.7/runpy.py\", line 176, in run_module\n    fname, loader, pkg_name)\n  File \"/usr/lib64/python2.7/runpy.py\", line 82, in _run_module_code\n    mod_name, mod_fname, mod_loader, pkg_name)\n  File \"/usr/lib64/python2.7/runpy.py\", line 72, in _run_code\n    exec code in run_globals\n  File \"/tmp/ansible_oci_object_storage_bucket_payload_yS9LtI/ansible_oci_object_storage_bucket_payload.zip/ansible_collections/oracle/oci/plugins/modules/oci_object_storage_bucket.py\", line 532, in <module>\n  File \"/tmp/ansible_oci_object_storage_bucket_payload_yS9LtI/ansible_oci_object_storage_bucket_payload.zip/ansible_collections/oracle/oci/plugins/modules/oci_object_storage_bucket.py\", line 522, in main\n  File \"/tmp/ansible_oci_object_storage_bucket_payload_yS9LtI/ansible_oci_object_storage_bucket_payload.zip/ansible_collections/oracle/oci/plugins/module_utils/oci_resource_utils.py\", line 901, in delete\n  File \"/tmp/ansible_oci_object_storage_bucket_payload_yS9LtI/ansible_oci_object_storage_bucket_payload.zip/ansible_collections/oracle/oci/plugins/module_utils/oci_object_storage_custom_helpers.py\", line 45, in get_resource\n  File \"/tmp/ansible_oci_object_storage_bucket_payload_yS9LtI/ansible_oci_object_storage_bucket_payload.zip/ansible_collections/oracle/oci/plugins/module_utils/oci_common_utils.py\", line 155, in call_with_backoff\n  File \"/usr/lib/python2.7/site-packages/oci/object_storage/object_storage_client.py\", line 1570, in get_bucket\n    \"Invalid value for `fields`, must be one of {0}\".format(fields_allowed_values)\nValueError: Invalid value for `fields`, must be one of ['approximateCount', 'approximateSize']\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

**Comment by rohnigam** [comment]
Hi @kasadasi ,

We are checking this.

**Comment by kasadasi** [comment]
Please find the tasks from the role,

---
# tasks file for oci_decomm_objectstorage
- name: 'Set bucket name fact'
  when:
    inventory_hostname is defined and
    inventory_hostname is search ('_decom')
  set_fact:
    bucket_name: '{{ outer_item|trim }}'
- name: 'Get the object storage namespace'
  collections:
     - oracle.oci
  delegate_to: 'localhost'
  oci_object_storage_namespace_facts:
     compartment_id: '{{ oci_config_tenancy }}'
     config_file_location: '{{ oci_local_homedir }}/.oci/config'
     config_profile_name: '{{ oci_tenancy }}_{{ oci_datacenter }}'
  register: namespace_facts
- name: 'Set namespace fact'
  when: >
     namespace_facts is defined
  set_fact:
    namespace_name: '{{ namespace_facts.namespace }}'
- name: 'Fetch details of objectstorage'
  collections:
     - oracle.oci
  when: >
    namespace_name is defined and
    namespace_name|length > 0 and
    bucket_name is defined and
    bucket_name|length > 0
  delegate_to: 'localhost'
  ignore_errors: 'true'
  oci_object_storage_bucket_facts:
     namespace_name: '{{ namespace_name }}'
     bucket_name: '{{ bucket_name }}'
     config_file_location: '{{ oci_local_homedir }}/.oci/config'
     config_profile_name: '{{ oci_tenancy }}_{{ oci_datacenter }}'
  register: bucket_results
- name: 'Fetch details of objects on {{ bucket_name }}'
  collections:
     - oracle.oci
  when: >
    namespace_name is defined and
    namespace_name|length > 0 and
    bucket_results is defined and
    bucket_name is defined and
    bucket_name|length > 0
  delegate_to: localhost
  ignore_errors: 'true'
  oci_object_storage_object_facts:
     namespace_name: '{{ namespace_name }}'
     bucket_name: '{{ bucket_name }}'
     config_file_location: '{{ oci_local_homedir }}/.oci/config'
     config_profile_name: '{{ oci_tenancy }}_{{ oci_datacenter }}'
  register: object_results
- name: 'Get bucket OCID'
  ignore_errors: 'true'
  when: >
    bucket_results is defined and
    bucket_name is defined
  set_fact:
    bucket_ocid: |
      {{ bucket_results.bukets |json_query("[?name=='" + bucket_name|trim + "']|[0].id") }}
- name: 'Bucket details'
  ignore_errors: 'true'
  when: >
    bucket_ocid is defined
  debug:
    msg: 'deleting the following bucket with all objects ....
         BUCKET-NAME: {{ bucket_results.buckets[0].name }}, NAMESPACE: {{ bucket_results.buckets[0].namespace }}, time_created: {{ bucket_results.buckets[0].time_created }}'
- name: 'Fetch list of preauthenticated_requests'
  collections:
    - oracle.oci
  delegate_to: localhost
  ignore_errors: 'true'
  oci_object_storage_preauthenticated_request_facts:
     namespace_name: '{{ namespace_name }}'
     bucket_name: '{{ bucket_name }}'
     config_file_location: '{{ oci_local_homedir }}/.oci/config'
     config_profile_name: '{{ oci_tenancy }}_{{ oci_datacenter }}'
  register: preauth_results
- name: 'Remove preauthenticated_requests of {{ bucket_name }}'
  collections:
     - oracle.oci
  when: >
    preauth_results is defined and
    preauth_results.preauthenticated_requests|length|int > 0
  delegate_to: localhost
  ignore_errors: 'true'
  oci_object_storage_preauthenticated_request:
    namespace_name: '{{ namespace_name }}'
    bucket_name: '{{ bucket_name }}'
    par_id: '{{ item.id }}'
    state: absent
    config_file_location: '{{ oci_local_homedir }}/.oci/config'
    config_profile_name: '{{ oci_tenancy }}_{{ oci_datacenter }}'
  loop: '{{ preauth_results.preauthenticated_requests }}'
  loop_control:
    label: '{{ item.name }}'
#- name: 'Deleting all objects on {{ bucket_name }}'
#  collections:
#     - oracle.oci
#  delegate_to: localhost
#  ignore_errors: 'true'
#  when: >
#    object_results is defined and
#    object_results.objects|length|int > 0
#  oci_object_storage_object:
#    namespace_name: '{{ namespace_name }}'
#    bucket_name: '{{ bucket_name }}'
#    object_name: "{{ item.name }}"
#    config_file_location: '{{ oci_local_homedir }}/.oci/config'
#    config_profile_name: '{{ oci_tenancy }}_{{ oci_datacenter }}'
#    state: absent
#  loop: '{{ object_results.objects }}'
#  loop_control:
#      label: '{{ item.name }}'
- name: 'Deleting bucket {{ bucket_name }}'
  collections:
     - oracle.oci
  delegate_to: localhost
  ignore_errors: 'true'
  when: >
    bucket_ocid is defined
  oci_object_storage_bucket:
     namespace_name: '{{ namespace_name }}'
     name: '{{ bucket_name }}'
     state: 'absent'
     #force: 'yes'
     config_file_location: '{{ oci_local_homedir }}/.oci/config'
     config_profile_name: '{{ oci_tenancy }}_{{ oci_datacenter }}'

**Comment by rohnigam** [comment]
@kasadasi 
Looks like your oci python sdk is not at the latest version. 
Can you please upgrade that as well ?
https://github.com/oracle/oci-python-sdk

**Comment by kasadasi** [comment]
Hi,

 Tested this with python 3.6.8 and getting following error. Request you to look at it and provide us the solution.

TASK [oci_collection_decomm_objectstorage_modified : Deleting bucket kathir-test-bucket] ******************************************************
Monday 21 June 2021  09:39:37 +0000 (0:00:00.034)       0:00:35.919 ***********
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ValueError: Invalid value for `fields`, must be one of ['approximateCount', 'approximateSize']
fatal: [aucuhca01_iad_decom_buckets_test]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1624268377.47-16061-245560875062615/AnsiballZ_oci_object_storage_bucket.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1624268377.47-16061-245560875062615/AnsiballZ_oci_object_storage_bucket.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1624268377.47-16061-245560875062615/AnsiballZ_oci_object_storage_bucket.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.oracle.oci.plugins.modules.oci_object_storage_bucket', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_oci_object_storage_bucket_payload_f8_admiw/ansible_oci_object_storage_bucket_payload.zip/ansible_collections/oracle/oci/plugins/modules/oci_object_storage_bucket.py\", line 532, in <module>\n  File \"/tmp/ansible_oci_object_storage_bucket_payload_f8_admiw/ansible_oci_object_storage_bucket_payload.zip/ansible_collections/oracle/oci/plugins/modules/oci_object_storage_bucket.py\", line 522, in main\n  File \"/tmp/ansible_oci_object_storage_bucket_payload_f8_admiw/ansible_oci_object_storage_bucket_payload.zip/ansible_collections/oracle/oci/plugins/module_utils/oci_resource_utils.py\", line 901, in delete\n  File \"/tmp/ansible_oci_object_storage_bucket_payload_f8_admiw/ansible_oci_object_storage_bucket_payload.zip/ansible_collections/oracle/oci/plugins/module_utils/oci_object_storage_custom_helpers.py\", line 45, in get_resource\n  File \"/tmp/ansible_oci_object_storage_bucket_payload_f8_admiw/ansible_oci_object_storage_bucket_payload.zip/ansible_collections/oracle/oci/plugins/module_utils/oci_common_utils.py\", line 155, in call_with_backoff\n  File \"/usr/local/lib/python3.6/site-packages/oci/object_storage/object_storage_client.py\", line 1514, in get_bucket\n    \"Invalid value for `fields`, must be one of {0}\".format(fields_allowed_values)\nValueError: Invalid value for `fields`, must be one of ['approximateCount', 'approximateSize']\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
...ignoring

**Comment by rohnigam** [comment]
Hi @kasadasi ,

Sure.

Can you please share with me the output for the following commands:

- `pip freeze | grep oci`
- `pip freeze | grep ansible`

**Comment by kasadasi** [comment]
Hi @rohnigam ,

 Please find details,

[root@omcscabzffscfa ~]# pip freeze | grep oci
/root/.local/lib/python2.7/site-packages/OpenSSL/crypto.py:12: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the next release.
  from cryptography import x509
oci==2.39.0
oci-cli==2.25.1
[root@omcscabzffscfa ~]# pip freeze | grep ansible
/root/.local/lib/python2.7/site-packages/OpenSSL/crypto.py:12: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the next release.
  from cryptography import x509
ansible==2.9.9
[root@omcscabzffscfa ~]#

Regards,
Kathirvel.S

**Comment by rohnigam** [comment]
Hey @kasadasi ,

It looks to me like you have multiple python environments on your system.

You mentioned that you are using python 3 but in pip freeze we see an error for python 2 as well.

I believe you must be having pip3 as well for python3's package management.

Can you check and pass your oci and ansible package versions with that ?

**Comment by kasadasi** [comment]
I was passing python3 as an extra vars and running a command like below, Will this not sufficient to work python3? Do I really need to setup virtualenv?

ansible-playbook vm_decom.yml --limit aucuhca01_iad_decom_buckets_test -e "ansible_python_interpreter=/bin/python3"

**Comment by rohnigam** [comment]
It is sufficient.

Just that oci and ansible versions that you've passed me are specific to the python2 environment.

Can you pass the output for following ?

- ```pip3 freeze | grep oci```
- ```pip3 freeze | grep ansible```

**Comment by kasadasi** [comment]
Please find the details below,

[root@omcscabzffscfa ~]# pip3 freeze | grep oci
oci==2.39.0
oci-cli==2.25.1
oci-utils==0.12.3
[root@omcscabzffscfa ~]# pip3 freeze | grep ansible
[root@omcscabzffscfa ~]#

**Comment by rohnigam** [comment]
Thanks for sharing.

Can you try ```pip3 install ansible``` ?

Also, do you have one or multiple python3 versions on your system ?

We have checked the traceback you shared at our end,
and we are convinced that its just an older version of python-sdk, that is the problem here.

If it still doesn't work, I'd suggest doing a fresh installation inside a virtualenv,
or uninstalling all packages and then installing them again.

**Comment by kasadasi** [comment]
This is the only production server which is being used for the all the tasks at our environment, So installing ansible via pip3 may impact existing tasks.

Yes, I do see multiple python3 versions in the system.

When I check SDK version by pip/pip3 I could see we have 2.39.0 which is latest. How do you say that we are having older version of SDK.

**Comment by rohnigam** [comment]
@kasadasi 

Can you share the output for the following ?

```/bin/python3 -c 'import oci; print(oci.__version__)'```

**Comment by kasadasi** [comment]
[root@omcscabzffscfa ~]# /bin/python3 -c ‘import oci; print(oci.__version__)’
2.39.0
[root@omcscabzffscfa ~]#

**Comment by manojmeda** [comment]
@kasadasi Looks like an environment issue. We are able to reproduce this error with an older version of python SDK. Would be better if we can have a call and debug the issue. Please let me know your contact details and a time when you can join the call. We will share the details with you.

**Comment by kasadasi** [comment]
We can have a call by tomorrow(25-Jun-21) by 3PM IST. Please let me know if you are okay to join at this time.

**Comment by manojmeda** [comment]
@kasadasi Sure 25th June 3PM works. Would zoom work for you? If so, we can setup a call and share the details.

**Comment by kasadasi** [comment]
Yes, zoom works for me. Please share the details.

**Comment by manojmeda** [comment]
@kasadasi Can you share your (and anyone who would be joining the call) contact details (email) with me (manoj.meda@oracle.com) and I will send the zoom details by email.

**Comment by kasadasi** [comment]
kathirvel.sadasivam@oracle.com,
vijayaprakash.krishnamoorthy@oracle.com

**Comment by kasadasi** [comment]
I have sent you an email.

**Comment by kasadasi** [comment]
@manojmeda @rohnigam ,

Thanks for the call.

I could confirm it is working now. Closing this ticket as resolved.

Regards,
Kathirvel.S

**Comment by kasadasi** [comment]
I could confirm it is working now. Closing this ticket as resolved.

Regards,
Kathirvel.S
