### ISSUE TITLE
Feature Request: Allow display_name to be used in hostname_format

### ISSUE THREAD

**Issue by DII-dsward** [oracle/oci-ansible-collection#64]
FQDN is not a satisfactory for our use case because the domain suffix does not match our internal DNS suffix. My companies DNS suffix is not oraclecloud.com. Please allow us to use display_name for the inventory plugin, so we can leverage our internal DNS for name resolution.

**Comment by manojmeda** [comment]
@DII-dsward We will include this feature in v2.21.0 which is planned on 6th May.

**Comment by sagar2938** [comment]
@DII-dsward , can you please confirm us if the display_name is the display_name of the compute instance?

**Comment by DII-dsward** [comment]
display_name should be used to pull db systems as well, but yes the display_name of the compute instance. Thank you.

**Comment by manojmeda** [comment]
@DII-dsward As per the discussion in the issue https://github.com/oracle/oci-ansible-collection/issues/66, we will not be implementing the display_name feature for db hosts. We will only implement this feature for compute instances for now.

**Comment by sagar2938** [comment]
@DII-dsward , allowing display_name in the hostname_format is included in the latest release (v2.21.0). Closing this issue.
