### ISSUE TITLE
Feature Request: Allow fetch_db_hosts inventory plugin to use hostname or display_name as hostname_format

### ISSUE THREAD

**Issue by DII-dsward** [oracle/oci-ansible-collection#66]
We would like to begin automating database system collection and configuration. Part of this means we would like to standardize our inventory collections using the name of the database system deployed in OCI.

**Comment by manojmeda** [comment]
@DII-dsward Just to be clear, you want the option to use the display_name of the db_system as the hostname for the db hosts. I assume this is an extension to the issue https://github.com/oracle/oci-ansible-collection/issues/64 for db hosts. 

A couple of problems with this approach:
Currently db host does not have a display_name but what if DBAAS API adds display_name option to the db host in the future.
There are other parent resources for a db host like db_home which also have a display_name and what if someone wants to use that instead.

I would suggest creating an issue to the DBAAS team to add display_name option to the db host and then we can support display_name as an option for db hosts.

**Comment by manojmeda** [comment]
@DII-dsward Just to clarify, we do pull the db nodes using the db systems but AFAIK a db node could be associated with other parent resources like db home, database etc which are part of a db system. I could be wrong.

**Comment by manojmeda** [comment]
@DII-dsward Closing this ticket since we cannot implement the feature unless the database host has a `display_name` attribute. Please create a feature request for DBAAS team. Once `display_name` is added to the db host, we will implement this feature in our inventory plugin.
