### ISSUE TITLE
Feature Request: Provide compose field to free-form vars

### ISSUE THREAD

**Issue by DII-dsward** [oracle/oci-ansible-collection#67]
We are not able to use the OCI plugin for windows and linux automation in one inventory. This is causing duplicate inventory entries for the same machine. We would like the ability to change the host vars during inventory pull with the plugin.

**Comment by DII-dsward** [comment]
Please reference 'compose' under inventory

https://docs.ansible.com/ansible/latest/plugins/inventory.html.

Our use case will do something like this
"{{ inventory_hostname.split('.')[0]+'.<domain.name>' }}"

**Comment by manojmeda** [comment]
@DII-dsward Thanks for bringing this to our notice. We are checking the `compose` option. Can you please elaborate more on what do you mean by`We are not able to use the OCI plugin for windows and linux automation in one inventory` so that we understand the use case properly.

**Comment by sagar2938** [comment]
@DII-dsward , You can use the compose option in OCI inventory plugin. I have tried it and I'm able to create host variables. Can you please give more details about what you are trying to achieve. PFB the sample using compose option in OCI inventory plugin.

plugin: oracle.oci.oci

regions:
  - us-ashburn-1

compose:
  avaibalility_domain_region: "availability_domain.split(':')[1]"

**Comment by DII-dsward** [comment]
We need to truncate the *.oraclevcn.com domain suffix to replace with our domain suffix. I did not see reference to it in the documentation, and working with redhat to troubleshoot Ansible Tower inventory configuration management it was determined that we are unable to leverage IP nor FQDN from the inventory plugin for configuration management. I will add the compose option to my db system and compute instance plugins pulling hostname and display_name respectively.

**Comment by DII-dsward** [comment]
I have not been able to change the hostname using compose. This is the dynamic inventory script.

---
# https://github.com/oracle/oci-ansible-collection/blob/master/docs/collections/oracle/oci/oci_inventory.rst
plugin: oracle.oci.oci
hostname_format: fqdn
enable_parallel_processing: yes
fetch_db_hosts: true
fetch_compute_hosts: false
regions:
  - us-ashburn-1
  - us-phoenix-1
compose:
ansible_host: fqdn.split(".")[0]+".domain.suffix"

**Comment by DII-dsward** [comment]
Can i use the hostnames option like this?

hostnames:
- 'display_name+"."+"domain.suffix"'
- 'hostname+"."+"domain.suffix"'

**Comment by sagar2938** [comment]
@DII-dsward , thanks for all the details. we are working on your requirement.

**Comment by sagar2938** [comment]
@DII-dsward , We have added new option "hostname_format_preferences" in inventory plugin. You can pass a list of Jinja2 expressions in order of precedence to compose inventory_hostname. You can find more details about the hostname_format_preferences here : https://oci-ansible-collection.readthedocs.io/en/latest/collections/oracle/oci/oci_inventory.html 

Now you can set your hostname the way you want by passing any valid Jinja expression to the hostname_format_preferences option. You can use all the available hostvars in your Jinja expression. Below is a sample playbook where we are concatenating display_name var in the hostvars with a string ".domain.com" and setting it as the hostname.

plugin: oracle.oci.oci

regions:
  - us-phoenix-1

hostname_format_preferences:
  - "display_name+'.domain.com'"

Please updated to the  latest version 2.23.0 to use hostname_format_preferences option.
