### ISSUE TITLE
View available dbaas storage size to scale up

### ISSUE THREAD

**Issue by kasadasi** [oracle/oci-ansible-collection#68]
## Issue Report

Is there module available to list down the available dbaas storage size which we can choose for storage scale up action.

On the console while doing storage scale up we see a drop down to choose next size to scale up, but the same not able to fetch using ansible modules.

A clear and concise description of what the issue is.

**Expected behavior**

**Environment**

* OS version:

* Ansible version:

    insert output of `ansible --version` here

* OCI Python SDK version:

    insert output of `python -c "import oci;print(oci.__version__)"` here

* OCI Ansible Modules version:

    insert output of (for oracle.oci):
`ansible-galaxy collection list`

**Ansible playbook to reproduce the issue**

    insert a sample playbook to reproduce the issue here(if relevant to the issue)

**Comment by manojmeda** [comment]
@kasadasi Could you please provide the below details for us to be able to help you better:

1) What kind of database are you creating? VM/BM etc.
2) Screenshots of the console page  or the API/CLI equivalent of what you are try to do and what information you see which will help us finding the corresponding ansible module easily.

**Comment by kasadasi** [comment]
Please find inline comments,

1. What kind of database are you creating? VM/BM etc.
        The DBAAS were already created which is VM, I would like to use the module to scale up the storage. I do see a module "oci_database_db_system" which does the scale storage up based on the size.

2. Screenshots of the console page or the API/CLI equivalent of what you are try to do and what information you see which will help us finding the corresponding ansible module easily.

 Please find below attached snapshot on which we can see available storage size. When I use ansible module "oci_database_db_system_facts" I can only pull the current storage size used by DBAAS, If I am able to see both current and available storage sizes I can do a comparison and choose the target one based on the current size. 
       
<img width="1440" alt="Screenshot 2021-04-28 at 11 19 03 AM" src="https://user-images.githubusercontent.com/76952035/116353005-b0dc3a80-a813-11eb-9c18-458f57dc13f6.png">


Please let me know if you need any more details

**Comment by bsushant-athena** [comment]
Hey, from [this documentation link](https://github.com/oracle/oci-ansible-collection/blob/master/docs/collections/oracle/oci/oci_database_db_system_facts_module.rst#parameters) I could see that the `oci_database_db_system_facts` module does return the `data_storage_size_in_gbs` which is `The data storage size, in gigabytes, that is currently available to the DB system. Applies only for virtual machine DB systems.`

**Comment by kasadasi** [comment]
Hi,
 Thanks for the response. I used this module and gathered data, I could see only what storage size is set to the DB system. But I am expecting is list of available storage size which I can use during storage scale up(Like above attached snap)

**Comment by bsushant-athena** [comment]
I do not think there is any such feature that returns a list of available storage. I would request you to check with the DBAAS team for this specific requirement.

**Comment by manojmeda** [comment]
@kasadasi This looks like ease of use enhancement added by the console team and not a feature supported by DBAAS API. If API does not support it, then ansible module also cannot since we depend on API for the information. Closing this issue.
