### ISSUE TITLE
Oracle Grid Infrastructure patching

### ISSUE THREAD

**Issue by gpitchai** [oracle/oci-ansible-collection#69]
Looking for Ansible Playbooks for Oracle Grid Infrastructure Patching
https://docs.oracle.com/en/database/oracle/oracle-database/19/cwlin/applying-patches-to-oracle-asm.html#GUID-FE981E6C-C517-406B-B66E-8323E3C4B6DC

**Comment by bsushant-athena** [comment]
We do not provide Ansible playbooks.
