### ISSUE TITLE
Oracle Database Patching for Exadata Cloud at Customer

### ISSUE THREAD

**Issue by gpitchai** [oracle/oci-ansible-collection#70]
Looking for Ansible playbooks for Oracle Database patching for Exadata Cloud at Customer
https://docs.oracle.com/en-us/iaas/Content/Database/Tasks/examanagingpatching.htm

**Comment by bsushant-athena** [comment]
@gpitchai we do not provide an ansible-playbook, but we will try to provide samples.

**Comment by bsushant-athena** [comment]
Closing this issue as we had a call with Ganesh regarding the same.
