### ISSUE TITLE
Oracle Database Upgrade in Exadata Cloud Service

### ISSUE THREAD

**Issue by gpitchai** [oracle/oci-ansible-collection#71]
Looking for Ansible Playbooks for Oracle Database upgrades in Exadata Cloud Service
https://docs.oracle.com/en-us/iaas/Content/Database/Tasks/exaupgrading.htm

**Comment by bsushant-athena** [comment]
@gpitchai we do not provide an ansible-playbook, but we will try to provide samples.
Similar to this one >> https://github.com/oracle/oci-ansible-collection/tree/master/samples/database/autonomous_database

**Comment by bsushant-athena** [comment]
I'm closing this ticket and the #70  is also related to Exadata Cloud Service.
