### ISSUE TITLE
FEATURE: consider auto-generated groups for DB System nodes based on System display-name

### ISSUE THREAD

**Issue by jeliker** [oracle/oci-ansible-collection#72]
When inventory for DB is retrieved via `fetch_db_hosts: yes` and `hostname_format: private_ip` it is difficult to select nodes for a single DB System. Please consider adding auto-generated groups such as `@_DB_SYS_NAME_Node#` for all DB System nodes.

Presently the inventory with `fetch_db_hosts: yes` and `hostname_format: fqdn` is recognizable such as this:

```
@all:
  |--@DB:
  |  |--ent-db1.dbsub.vcn1.oraclevcn.com
  |  |--ent-db2. dbsub.vcn1.oraclevcn.com
  |--@_ocid1_compartment_oc1__aaaaaaaafhu5qc37jdcfsc4kvyg4il7bunl4wsezjy37eevb6j5ro4plv5pq:
  |  |--ent-db1.dbsub.vcn1.oraclevcn.com
  |  |--ent-db2.dbsub.vcn1.oraclevcn.com
  |--@all_hosts:
  |  |--ent-db1.dbsub.vcn1.oraclevcn.com
  |  |--ent-db2.dbsub.vcn1.oraclevcn.com
  |--@db_hosts:
  |  |--ent-db1.dbsub.vcn1.oraclevcn.com
  |  |--ent-db2.dbsub.vcn1.oraclevcn.com
  |--@jpgn_US-ASHBURN-AD-1:
  |  |--ent-db1.dbsub.vcn1.oraclevcn.com
  |  |--ent-db2.dbsub.vcn1.oraclevcn.com
  |--@region_us-ashburn-1:
  |  |--ent-db1.dbsub.vcn1.oraclevcn.com
  |  |--ent-db2.dbsub.vcn1.oraclevcn.com
  |--@ungrouped:
```
In the above, a playbook could select like this:
```
- name: Node configuration for ENT DB System
  hosts: ~ent-db[0-9].dbsub.vcn1.oraclevcn.com
```
However, with `hostname_format: private_ip` it's nearly impossible to know which nodes are for which DB System with inventory that appears like this:
```
@all:
  |--@DB:
  |  |--10.2.12.176
  |  |--10.2.12.20
  |--@_ocid1_compartment_oc1__aaaaaaaafhu5qc37jdcfsc4kvyg4il7bunl4wsezjy37eevb6j5ro4plv5pq:
  |  |--10.2.12.176
  |  |--10.2.12.20
  |--@all_hosts:
  |  |--10.2.12.176
  |  |--10.2.12.20
  |--@db_hosts:
  |  |--10.2.12.176
  |  |--10.2.12.20
  |--@jpgn_US-ASHBURN-AD-1:
  |  |--10.2.12.176
  |  |--10.2.12.20
  |--@region_us-ashburn-1:
  |  |--10.2.12.176
  |  |--10.2.12.20
  |--@ungrouped:
```
I'd suggest the groups noted at the top of this post so output for `hostname_format: private_ip` would come out like this:
```
@all:
  |--@DB:
  |  |--10.2.12.176
  |  |--10.2.12.20
  |--@_ENT_DB_Node1:
  |  |--10.2.12.176
  |--@_ENT_DB_Node2:
  |  |--10.2.12.20
  |--@_ocid1_compartment_oc1__aaaaaaaafhu5qc37jdcfsc4kvyg4il7bunl4wsezjy37eevb6j5ro4plv5pq:
  |  |--10.2.12.176
  |  |--10.2.12.20
  |--@all_hosts:
  |  |--10.2.12.176
  |  |--10.2.12.20
  |--@db_hosts:
  |  |--10.2.12.176
  |  |--10.2.12.20
  |--@jpgn_US-ASHBURN-AD-1:
  |  |--10.2.12.176
  |  |--10.2.12.20
  |--@region_us-ashburn-1:
  |  |--10.2.12.176
  |  |--10.2.12.20
  |--@ungrouped:
```
…where `_ENT_DB` above comes from a DB System with display-name "ENT_DB." A change like this would allow playbook host selector like this example:
```
- name: Node configuration for ENT DB System
  hosts: ~_ENT_DB_Node[0-9]
```

**Comment by sushant91265** [comment]
Thanks for pointing out this, we will create an internal ticket and start working on it.
I'll update you once we are ready with this change, which will most likely happen in release v2.22 (Dtd: 20th May)

**Comment by bsushant-athena** [comment]
Thanks for pointing out this, we will create an internal ticket and start working on it.
I'll update you once we are ready with this change, which will most likely happen in release v2.22 (Dtd: 20th May)

**Comment by sagar2938** [comment]
@jeliker , we are adding db system display name in the hostvars in the next release v2.22 (Dtd: 20th May). You can use keyed_groups to group based on the db_system_name. Will this suffice your requirement?

keyed_groups:
  - key: db_system_name
    prefix: "DB_SYSTEM_"

**Comment by jeliker** [comment]
That sounds like a good approach. Really any solution that allows for names not IP addresses is good for me.

Thank you for pursing this!

**Comment by manojmeda** [comment]
@jeliker We added the db system display name (db_system_display_name) to the hostvars for db hosts. So you should be able to do below to create groups based on db system display name:

keyed_groups:
- key: db_system_display_name
   prefix: "DB_SYSTEM_"

**Comment by manojmeda** [comment]
@jeliker Closing the issue since the feature is added in the latest version (v2.22.0).
