### ISSUE TITLE
secret_rules on oci_vault_secret should not be provided (if no rules will be created)

### ISSUE THREAD

**Issue by desaes-br** [oracle/oci-ansible-collection#73]
https://github.com/oracle/oci-ansible-collection/blob/7c60d57663f334ad67317fed82c9f6f7ad375b44/plugins/modules/oci_vault_secret.py#L185

The example:
- name: Create secret
  oci_vault_secret:
    vault_id: "vault_OCID"
    secret_rules: "[]"
    compartment_id: ""
    secret_name: "testSecret"
    description: "my test secret"
    key_id: "key_OCID"
    secret_content:
      content: "base64_encoded_secret_contents"
      content_type: "BASE64"

will fail with the error:
fatal: [host]: FAILED! => {"changed": false, "msg": "Failure when processing no_log parameters. Module invocation will be hidden. dictionary requested, could not parse JSON or key=value"}

As secret_rules is an optional argument to create a secret we should remove it from the doc, since we can create the secret properly like:
- name: Create secret
  oci_vault_secret:
    vault_id: "vault_OCID"
    compartment_id: ""
    secret_name: "testSecret"
    description: "my test secret"
    key_id: "key_OCID"
    secret_content:
      content: "base64_encoded_secret_contents"
      content_type: "BASE64"

**Comment by bsushant-athena** [comment]
thank for pointing out this, we will create an internal ticket and start working on it.

**Comment by bsushant-athena** [comment]
@desaes-br  if you use it in the below way, it works. `secret_rules` is of type list.

name: Create secret
oci_vault_secret:
vault_id: "vault_OCID"
secret_rules: []
compartment_id: ""
secret_name: "testSecret"
description: "my test secret"
key_id: "key_OCID"
secret_content:
content: "base64_encoded_secret_contents"
content_type: "BASE64"

we will update the documentation accordingly.

**Comment by manojmeda** [comment]
The doc issue is fixed in the latest release (v2.22.0).
