### ISSUE TITLE
How does the "Tenancy specific configuration" looks like?

### ISSUE THREAD

**Issue by LorenzKeller** [oracle/oci-ansible-collection#75]
Dear,
it sounds trivial:
how do I insert the variables
--
SAMPLE_COMPARTMENT_OCID=ocid1.compartment.oc1...
SAMPLE_IMAGE_OCID=ocid1.image.oc1.eu-frankfurt-1.aaaaaaaac6narhzzt6k46dnyvh5yiqjp5buveyf62qwyegimgduyhikb2vca
SAMPLE_AD_NAME=jtzg:EU-FRANKFURT-1-AD-2
--
into the sample yaml file, for example the "launch-compute_instance" girl?

Before I have tried with an "env" file. Although they are present in the environment:
--
echo $SAMPLE_AD_NAME
jtzg:EU-FRANKFURT-1-AD-2
--
I still get an error:
--
failed: [localhost] (item=SAMPLE_COMPARTMENT_OCID) => {"ansible_loop_var": "item", "changed": false, "item": "SAMPLE_COMPARTMENT_OCID", "msg": "Environment variable SAMPLE_COMPARTMENT_OCID not set. Please declare an environment variable with an appropriate value for the sample to work."}
failed: [localhost] (item=SAMPLE_IMAGE_OCID) => {"ansible_loop_var": "item", "changed": false, "item": "SAMPLE_IMAGE_OCID", "msg": "Environment variable SAMPLE_IMAGE_OCID not set. Please declare an environment variable with an appropriate value for the sample to work."}
failed: [localhost] (item=SAMPLE_AD_NAME) => {"ansible_loop_var": "item", "changed": false, "item": "SAMPLE_AD_NAME", "msg": "Environment variable SAMPLE_AD_NAME not set. Please declare an environment variable with an appropriate value for the sample to work."}
--
Help is appreciated!
Kind regards
Lorenz

**Comment by rohan033** [comment]
Hey Lorenz,
Can you try exporting the variables by using the following commands.
For example:
```
export SAMPLE_COMPARTMENT_OCID=ocid1.compartment.oc1...
export SAMPLE_IMAGE_OCID=ocid1.image.oc1.eu-frankfurt-
export SAMPLE_AD_NAME=jtzg:EU-FRANKFURT-1-AD-2
```
Let us know if you still face the same issue.

Thanks.

**Comment by LorenzKeller** [comment]
Thanks for your quick reply!
I have done this:
--
$ ls
README.md		check_network.yml	setup.yaml		templates
ansible_env		sample.yaml		teardown.yaml
$ . ./ansible_env 
$ echo $SAMPLE_IMAGE_OCID
ocid1.image.oc1.eu-frankfurt-1.aaaaaaaac6narhzzt6k46dnyvh5yiqjp5buveyf62qwyegimgduyhikb2vca
$
--
$ ansible-playbook sample.yaml
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

PLAY [Launch a compute instance and connect to it using SSH] *****************************************************************

TASK [Gathering Facts] *******************************************************************************************************
ok: [localhost]

TASK [Check pre-requisites] **************************************************************************************************
failed: [localhost] (item=SAMPLE_COMPARTMENT_OCID) => {"ansible_loop_var": "item", "changed": false, "item": "SAMPLE_COMPARTMENT_OCID", "msg": "Environment variable SAMPLE_COMPARTMENT_OCID not set. Please declare an environment variable with an appropriate value for the sample to work."}
failed: [localhost] (item=SAMPLE_IMAGE_OCID) => {"ansible_loop_var": "item", "changed": false, "item": "SAMPLE_IMAGE_OCID", "msg": "Environment variable SAMPLE_IMAGE_OCID not set. Please declare an environment variable with an appropriate value for the sample to work."}
failed: [localhost] (item=SAMPLE_AD_NAME) => {"ansible_loop_var": "item", "changed": false, "item": "SAMPLE_AD_NAME", "msg": "Environment variable SAMPLE_AD_NAME not set. Please declare an environment variable with an appropriate value for the sample to work."}

PLAY RECAP *******************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

--
Kind regards
Lorenz

**Comment by rohan033** [comment]
Hey,
Can you confirm if you used the following commands before running the sample playbook.
```
export SAMPLE_COMPARTMENT_OCID=ocid1.compartment.oc1...
export SAMPLE_IMAGE_OCID=ocid1.image.oc1.eu-frankfurt-
export SAMPLE_AD_NAME=jtzg:EU-FRANKFURT-1-AD-2
```

`export` will set the environment variables which can be used by child process (here `ansible-playbook`) of the shell.
I think you are currently setting it without using `export` like `SAMPLE_IMAGE_OCID=ocid1.image.oc1.eu-frankfurt-` which are not being picked by the `ansible-playbook` command.

Can you try the following steps to run the playbook:

1: a
```
export SAMPLE_COMPARTMENT_OCID=ocid1.compartment.oc1...
export SAMPLE_IMAGE_OCID=ocid1.image.oc1.eu-frankfurt-
export SAMPLE_AD_NAME=jtzg:EU-FRANKFURT-1-AD-2
```
(1: b Optional)
`env | grep 'SAMPLE_COMPARTMENT_OCID'`

2:
```
ansible-playbook sample.yaml
```

**Comment by LorenzKeller** [comment]
Dear Rohan,
you are right. I have set it without "export"!
How could that happen to me ???
Now I am one step further:
--
$ ansible-playbook sample.yaml
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

PLAY [Launch a compute instance and connect to it using SSH] *****************************************************************

TASK [Gathering Facts] *******************************************************************************************************
ok: [localhost]

TASK [Check pre-requisites] **************************************************************************************************
skipping: [localhost] => (item=SAMPLE_COMPARTMENT_OCID) 
skipping: [localhost] => (item=SAMPLE_IMAGE_OCID) 
skipping: [localhost] => (item=SAMPLE_AD_NAME) 

TASK [Create a temporary directory to house a temporary SSH keypair we will later use to connect to instance] ****************
changed: [localhost]

TASK [set_fact] **************************************************************************************************************
ok: [localhost]

TASK [Generate a Private Key] ************************************************************************************************
changed: [localhost]

TASK [set_fact] **************************************************************************************************************
ok: [localhost]

TASK [Generate a Public Key] *************************************************************************************************
changed: [localhost]

TASK [Create a VCN] **********************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "oci python sdk required for this module."}

PLAY RECAP *******************************************************************************************************************
localhost                  : ok=6    changed=3    unreachable=0    failed=1    skipped=1    rescued=0    ignored=0   

Thanks!
--
Kind regards
Lorenz

**Comment by rohan033** [comment]
No worries.

The error is self explanatory.
Install oci python sdk using pip. Command `pip install oci`. 
(You will need `pip` dependency installed to run this command.)


Please refer this too: https://github.com/oracle/oci-ansible-collection/blob/master/COMMON_ISSUES.md
