### ISSUE TITLE
private_primary_ip not available in oci_database_db_node_facts

### ISSUE THREAD

**Issue by DII-dsward** [oracle/oci-ansible-collection#78]
Pulling dynamic inventory, the hostvar 'private_primary_ip' is available. Pulling the facts with the db_node module 'oci_database_db_node_facts' does not provide public or private ips. I have also checked 'oci_database_db_system_facts' for 'private_ip' and is not available.

**Comment by manojmeda** [comment]
@DII-dsward You can get the `vnic_id` of a db node from `oci_database_db_node_facts` module and then call `oci_network_vnic_facts` module to get the IP information like private_ip, public_ip etc.

**Comment by DII-dsward** [comment]
I do not like making extra calls where its not required. Should i submit a feature request here to have private_ip made available in oci_database_db_node_facts? Or is it not possible because its not exposed in the API?

**Comment by manojmeda** [comment]
@DII-dsward Yes you can submit a feature request here. It is possible and we will evaluate it. 

PS: We have done something similar for compute instance.

**Comment by manojmeda** [comment]
Closing this issue since a feature request (https://github.com/oracle/oci-ansible-collection/issues/80) has been created for the same.
