### ISSUE TITLE
How do i exclude compartments in the dynamic inventory plugin

### ISSUE THREAD

**Issue by DII-dsward** [oracle/oci-ansible-collection#79]
I need to exclude a compartment or hostname from the dynamic inventory collection. Can i use exclude_host_filters: as an example?

**Comment by manojmeda** [comment]
@DII-dsward Currently we don't provide a way of excluding compartments. But you can only pass the compartments using the `compartments` option. Also you can use `filters` to only generate inventory for specific resources.

But I understand that to be able to exclude specific compartments/hosts is a better approach. We will check and get back to you.

**Comment by DII-dsward** [comment]
Thanks, but we have far too many compartments to single them out. I was thinking of using a tag, but that doesn't seem as programmatic. I'm essentially just wanting to exclude security and network appliances from being pulled into our inventory. I will submit feature request for this.
