### ISSUE TITLE
Feature Request: Please add primary_private_ip to oci_database_db_system_facts

### ISSUE THREAD

**Issue by DII-dsward** [oracle/oci-ansible-collection#80]
Would like to be able to reference the primary_private_ip from oci_database_db_system_facts or oci_database_db_node_facts

**Comment by manojmeda** [comment]
@DII-dsward Thanks for creating the feature request. We will evaluate and get back to you.

**Comment by manojmeda** [comment]
@DII-dsward We added the IP information to the oci_database_db_node_facts module in the latest release (v2.22.0). The ip info is available in the fields `primary_public_ip` and `primary_private_ip`.
