### ISSUE TITLE
How to delete resources created by sample playbook?

### ISSUE THREAD

**Issue by LorenzKeller** [oracle/oci-ansible-collection#83]
Dear,
I am starting using Ansible with OCI. I can run a sample playbook. I have the OCI Ansible inventory plugin working.
When I excecute the "private_subnets_with_vpn" it creates the resources and at the ent it destroys VCN, Subnets etc.
Now I comment out the import task in the sample file, as suggested:
#import_tasks: teardown.yaml
I execute:
ansible-playbook-3 sample.yaml
--
localhost                  : ok=11   changed=0    unreachable=0    failed=1    skipped=0    rescued=1    ignored=7
--
Ok so far.
But what is the concept to destroy the created resources now?

Kind regards
Lorenz

**Comment by rohan033** [comment]
`#import_tasks: teardown.yaml` Un-comment this line and run the playbook again

**Comment by manojmeda** [comment]
@LorenzKeller Hopefully the provided solution worked. Closing the ticket. Please feel free to reopen or create another issue in case of any issues.

**Comment by LorenzKeller** [comment]
Dear,
this is not working for me.
When I re-run the sample.yml with Un-comment #import_tasks: teardown.yaml, it creates a 2nd instance, and terminates it again. The initial instance remain, as all networking components:
--

PLAY RECAP *******************************************************************************************************************************************************
localhost                  : ok=32   changed=10   unreachable=0    failed=0    skipped=1    rescued=0    ignored=0   

[opc@ansible3 launch_compute_instance]$ vi sample.yaml 
[opc@ansible3 launch_compute_instance]$ ansible-playbook sample.yaml 

PLAY [Launch a compute instance and connect to it using SSH] *****************************************************************************************************

TASK [Gathering Facts] *******************************************************************************************************************************************
ok: [localhost]

TASK [Check pre-requisites] **************************************************************************************************************************************
skipping: [localhost] => (item=SAMPLE_COMPARTMENT_OCID) 
skipping: [localhost] => (item=SAMPLE_IMAGE_OCID) 
skipping: [localhost] => (item=SAMPLE_AD_NAME) 

TASK [Create a temporary directory to house a temporary SSH keypair we will later use to connect to instance] ****************************************************
changed: [localhost]

TASK [set_fact] **************************************************************************************************************************************************
ok: [localhost]

TASK [Generate a Private Key] ************************************************************************************************************************************
changed: [localhost]

TASK [set_fact] **************************************************************************************************************************************************
ok: [localhost]

TASK [Generate a Public Key] *************************************************************************************************************************************
changed: [localhost]

TASK [Create a VCN] **********************************************************************************************************************************************
ok: [localhost]

TASK [set_fact] **************************************************************************************************************************************************
ok: [localhost]

TASK [Create a new Internet Gateway] *****************************************************************************************************************************
ok: [localhost]

TASK [set_fact] **************************************************************************************************************************************************
ok: [localhost]

TASK [Create route table to connect internet gateway to the VCN] *************************************************************************************************
ok: [localhost]

TASK [set_fact] **************************************************************************************************************************************************
ok: [localhost]

TASK [create ingress rules yaml body] ****************************************************************************************************************************
ok: [localhost]

TASK [create egress yaml body] ***********************************************************************************************************************************
ok: [localhost]

TASK [load the variables defined in the ingress rules yaml body] *************************************************************************************************
ok: [localhost]

TASK [print loaded_ingress] **************************************************************************************************************************************
ok: [localhost] => {
    "msg": "loaded ingress is {u'instance_ingress_security_rules': [{u'source': u'0.0.0.0/0', u'protocol': u'6', u'tcp_options': {u'destination_port_range': {u'max': 22, u'min': 22}}}]}"
}

TASK [load the variables defined in the egress rules yaml body] **************************************************************************************************
ok: [localhost]

TASK [print loaded_egress] ***************************************************************************************************************************************
ok: [localhost] => {
    "msg": "loaded egress is {u'instance_egress_security_rules': [{u'tcp_options': {u'destination_port_range': {u'max': 22, u'min': 22}}, u'destination': u'0.0.0.0/0', u'protocol': u'6'}]}"
}

TASK [Create a security list for allowing access to public instance] *********************************************************************************************
ok: [localhost]

TASK [set_fact] **************************************************************************************************************************************************
ok: [localhost]

TASK [Create a subnet to host the public instance. Link security_list and route_table.] **************************************************************************
ok: [localhost]

TASK [set_fact] **************************************************************************************************************************************************
ok: [localhost]

TASK [Launch an instance] ****************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Work request ocid1.coreservicesworkrequest.oc1.eu-frankfurt-1.abtheljscw5dezufzd4nte62fjx3ippyq7xwd5ssmciv5oxpb3fwjk3dx2dq failed with errors: [{\n  \"code\": \"vcn-error\", \n  \"message\": \"A problem occurred while preparing the instance's VNIC.  (Hostname mytestinstance is already used in subnet ocid1.subnet.oc1.eu-frankfurt-1.aaaaaaaadvqukq2vnyumr5bflldjsrdfpyftk6adp4v5ep24bvi5etryir7q)\", \n  \"timestamp\": \"2021-05-24T11:11:53.986000+00:00\"\n}]"}

PLAY RECAP *******************************************************************************************************************************************************
localhost                  : ok=22   changed=3    unreachable=0    failed=1    skipped=1    rescued=0    ignored=0   
--
What am I doing wrong?

**Comment by rohnigam** [comment]
Hi @LorenzKeller 

We checked this, you are not doing anything wrong.
For now you can delete the resources manually.

But thanks for pointing this out, we'll fix it in this release
so that when we run this sample the second time, 
like the way it was mentioned in the previous exchanges,
the resources created as part of the first run are deleted.

**Comment by LorenzKeller** [comment]
Great! Thanks!

**Comment by rohnigam** [comment]
Hi @LorenzKeller ,

This sample has now been updated.

You can follow the steps [here](https://github.com/oracle/oci-ansible-collection/tree/master/samples/compute/launch_compute_instance)
to achieve the desired result.

Please let us know, if any further concerns.
