### ISSUE TITLE
Link on docs page to github is broken

### ISSUE THREAD

**Issue by joestechland** [oracle/oci-ansible-collection#84]
https://docs.oracle.com/en-us/iaas/Content/API/SDKDocs/ansiblesamples.htm#Sample_Ansible_Playbooks

https://github.com/oracle/oci-ansible-collection/tree/master/solutions/oci-ansible-free-master

is broken

**Comment by manojmeda** [comment]
@joestechland Thanks for pointing it out. We will correct the documentation. Meanwhile you can use [this](https://github.com/oracle/oci-ansible-collection/tree/master/solutions/oci-cloudnative).

**Comment by rohnigam** [comment]
The link has been corrected
