### ISSUE TITLE
oci_object_storage_bucket fails with ValueError: Invalid value for `fields`, must be one of ['approximateCount', 'approximateSize'] when using 2.24.0

### ISSUE THREAD

**Issue by mayanala-coxauto** [oracle/oci-ansible-collection#88]
## Issue Report

**Describe the issue**

We have an existing code that works successfully in 2.9 for creating buckets. 
But after we changed to using collections 2.23.0 or 2.24.0 is giving following error.
The error was: ValueError: Invalid value for `fields`, must be one of ['approximateCount', 'approximateSize']

**Expected behavior**

Playbook is supposed to create bucket without failure

**Environment**

* OS version: Oracle Linux Server release 7.9

* Ansible version:

ansible 2.9.23
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/shared/mayanala/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Mar 12 2021, 14:55:44) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44.0.3)]

* OCI Python SDK version:

    2.23.0

* OCI Ansible Modules version:

    insert output of (for oracle.oci):
`ansible-galaxy collection list`

Getting error when trying to run list command but installed collections 2.24
ansible-galaxy collection list
usage: ansible-galaxy collection [-h] COLLECTION_ACTION ...
ansible-galaxy collection: error: argument COLLECTION_ACTION: invalid choice: u'list' (choose from 'init', 'build', 'publish', 'install')

**Ansible playbook to reproduce the issue**

sample playbook:

---

- hosts: localhost
  connection: local
  gather_facts: no

  tasks:
  - name: Create bucket
    oracle.oci.oci_object_storage_bucket:
      namespace_name: "coxautoinc"
      compartment_id: "ocid1.compartment.oc1..xxxxx"
      name: test-new
      public_access_type: 'NoPublicAccess'
      metadata:
              project: 'Test bucket from ansible module'
      state: 'present'
    register: oci_create_bucket_reg

  - debug:
      msg: "{{ oci_create_bucket_reg }}"

Output:
--------

[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

PLAY [localhost] *****************************************************************************************************************************************************

TASK [Create bucket] *************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ValueError: Invalid value for `fields`, must be one of ['approximateCount', 'approximateSize']
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/home/shared/mayanala/.ansible/tmp/ansible-tmp-1625108621.67-31332-253554784127915/AnsiballZ_oci_object_storage_bucket.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/shared/mayanala/.ansible/tmp/ansible-tmp-1625108621.67-31332-253554784127915/AnsiballZ_oci_object_storage_bucket.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/shared/mayanala/.ansible/tmp/ansible-tmp-1625108621.67-31332-253554784127915/AnsiballZ_oci_object_storage_bucket.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.oracle.oci.plugins.modules.oci_object_storage_bucket', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python2.7/runpy.py\", line 176, in run_module\n    fname, loader, pkg_name)\n  File \"/usr/lib64/python2.7/runpy.py\", line 82, in _run_module_code\n    mod_name, mod_fname, mod_loader, pkg_name)\n  File \"/usr/lib64/python2.7/runpy.py\", line 72, in _run_code\n    exec code in run_globals\n  File \"/tmp/ansible_oracle.oci.oci_object_storage_bucket_payload_wiAJQb/ansible_oracle.oci.oci_object_storage_bucket_payload.zip/ansible_collections/oracle/oci/plugins/modules/oci_object_storage_bucket.py\", line 532, in <module>\n  File \"/tmp/ansible_oracle.oci.oci_object_storage_bucket_payload_wiAJQb/ansible_oracle.oci.oci_object_storage_bucket_payload.zip/ansible_collections/oracle/oci/plugins/modules/oci_object_storage_bucket.py\", line 523, in main\n  File \"/tmp/ansible_oracle.oci.oci_object_storage_bucket_payload_wiAJQb/ansible_oracle.oci.oci_object_storage_bucket_payload.zip/ansible_collections/oracle/oci/plugins/modules/oci_object_storage_bucket.py\", line 408, in is_update\n  File \"/tmp/ansible_oracle.oci.oci_object_storage_bucket_payload_wiAJQb/ansible_oracle.oci.oci_object_storage_bucket_payload.zip/ansible_collections/oracle/oci/plugins/module_utils/oci_resource_utils.py\", line 471, in does_resource_exist\n  File \"/tmp/ansible_oracle.oci.oci_object_storage_bucket_payload_wiAJQb/ansible_oracle.oci.oci_object_storage_bucket_payload.zip/ansible_collections/oracle/oci/plugins/module_utils/oci_object_storage_custom_helpers.py\", line 45, in get_resource\n  File \"/tmp/ansible_oracle.oci.oci_object_storage_bucket_payload_wiAJQb/ansible_oracle.oci.oci_object_storage_bucket_payload.zip/ansible_collections/oracle/oci/plugins/module_utils/oci_common_utils.py\", line 158, in call_with_backoff\n  File \"/usr/lib/python2.7/site-packages/oci/object_storage/object_storage_client.py\", line 1518, in get_bucket\n    \"Invalid value for `fields`, must be one of {0}\".format(fields_allowed_values)\nValueError: Invalid value for `fields`, must be one of ['approximateCount', 'approximateSize']\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

PLAY RECAP ***********************************************************************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

**Comment by rohnigam** [comment]
hi @mayanala-coxauto ,

Couple of things:
1. Python 2 was EOL long back.   
  OCI Ansible Collections requires python >= 3.6.
  You can find it in the docs here
  https://oci-ansible-collection.readthedocs.io/en/latest/collections/oracle/oci/oci_object_storage_bucket_module.html#requirements
  Please upgrade your python version

2. Please upgrade your python-sdk to the latest version.
https://github.com/oracle/oci-python-sdk

**Comment by manojmeda** [comment]
@mayanala-coxauto As a rule of thumb, you should upgrade the OCI python SDK as well when you upgrade OCI Ansible collection since there might be new features that are added that work only with the latest version of python SDK.

That is why we always have the below in every release changelog:

```
Changed
Please update to the latest version of OCI Python SDK
```

**Comment by mayanala-coxauto** [comment]
Thanks for the feedback ! We will test with latest version of OCI Python SDK.

**Comment by mayanala-coxauto** [comment]
This worked after using latest version of OCI Python SDK. Thank you !
