### ISSUE TITLE
oci_compute_instance not returning results

### ISSUE THREAD

**Issue by binbashroot** [oracle/oci-ansible-collection#9]
When running using the oci_compute_module,  Results are not being registered even though I am using the register function in Ansible.

 ansible --version
ansible 2.9.9
  config file = /home/usera/.ansible.cfg
  configured module search path = [u'/home/usera/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Nov 27 2019, 09:57:45) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39.0.1)]

OCI  collection 2.1.2-beta

playbook.yml 
```
---
     - name: Create a new instance in the target compartment using the 100G base image
       oci_compute_instance:
         display_name: "{{ th }}"
         availability_domain: "dRfu:US-ASHBURN-AD-1"
         compartment_id: "{{ tc }}"
         shape: "{{ tshape }}"
         source_details:
             source_type: image
             image_id: xxxxxxxxx
         create_vnic_details:
             hostname_label: "{{ th }}"
             subnet_id: "{{ subnet_to_use }}"
       register: th_status
       environment:
            OCI_USE_NAME_AS_IDENTIFIER: 1
    
    - debug:
          var: th_status


Results yielded:
TASK [Create a new instance *******************************************************************
changed: [localhost]

TASK [debug] *******
ok: [localhost] => {
    "th_status": {
        "changed": false,
        "skip_reason": "Conditional result was False",
        "skipped": true
    }
}
```

**Comment by mross22** [comment]
@binbashroot just to double check, you don't have any `when` clause for your create instance block, correct?

The output suggests that block is being skipped and thus no results are being returned.

**Comment by binbashroot** [comment]
@mross22.  You're absolutely right.  I totally missed that I had another task that had that same register var.  Profuse apologies for my error.
