### ISSUE TITLE
oci_database_db_home doesn't create new db home in Exadata VM Cluster 2 if same name db home exists in Exadata VM Cluster 1

### ISSUE THREAD

**Issue by mayanala-coxauto** [oracle/oci-ansible-collection#91]
## Issue Report

I created following 
Exadata InfraStructure 1  - infra-exa-iad1-inf1
Exadata VM Cluster 1       - infra-exa-iad1-inf1
DB Home (display name) -  imebs
DB name (display name)  - imebs

Then I started creating 
Exadata InfraStructure 2  - infra-exa-iad1-inf2
Exadata VM Cluster 2      - infra-exa-iad1-inf2
DB Home (display name) -  imebs
DB name (display name)  - imebs

When creating DB home under Exadata VM Cluster 2, the ansible module oci_database_db_home doesn't create it as it picks up 'imebs' db_home_id from Exadata VM Cluster 1. It works fine when doing so from OCI Console.

**Expected behavior**
To be able to create same names dbhome and db name on different Exadata VM cluster

**Environment**

OS version: Oracle Linux Server release 7.9

Ansible version:

ansible 2.9.23
config file = /etc/ansible/ansible.cfg
configured module search path = [u'/home/shared/mayanala/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
ansible python module location = /usr/lib/python2.7/site-packages/ansible
executable location = /usr/bin/ansible
python version = 2.7.5 (default, Mar 12 2021, 14:55:44) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44.0.3)]

OCI Python SDK version:

2.23.0

OCI Ansible Modules version:

insert output of (for oracle.oci):
ansible-galaxy collection list

Getting error when trying to run list command but installed collections 2.23
ansible-galaxy collection list
usage: ansible-galaxy collection [-h] COLLECTION_ACTION ...
ansible-galaxy collection: error: argument COLLECTION_ACTION: invalid choice: u'list' (choose from 'init', 'build', 'publish', 'install')

**Ansible playbook to reproduce the issue**

Attached is the 
[oci_database_db_home_output.txt](https://github.com/oracle/oci-ansible-collection/files/6799026/oci_database_db_home_output.txt)
output from the playbook with OCIDs that indicate what has been invoked and what has been returned.

Please note the vm_cluster_id difference in invocation and what was returned at the top of the output.

**Comment by rohnigam** [comment]
Hi @mayanala-coxauto ,

I see from the logs that you are using key-by

```
"invocation": {
    "module_args": {
            "compartment_id": "ocid1.compartment.oc1..aaaaaaaati6qedrxemkwziahsgxsmzzip4boqcbs7dwtybpknthfauelqh4a",
            "vm_cluster_id": "ocid1.cloudvmcluster.oc1.iad.abuwcljr3xi3hvjpbdvppx7i7novp3jgxckh6brm4nk377e57vozaublwgda",
            "display_name": "imebs",
            "key_by": [
                "display_name"                      <<<<<< This
            ],
            "source": "VM_CLUSTER_NEW",
            "database": {
```

This is the reason that only name is being considered for checking if the resource already exists.

For the ```vm_cluster_id``` to be honoured as well, you can include that in ```key_by``` or remove the key_by itself.

**Comment by mayanala-coxauto** [comment]
Thanks for the tip. That worked !
