### ISSUE TITLE
oci_database_db_home - state present created db home and db as well but state absent does not do both db home and db. 

### ISSUE THREAD

**Issue by mayanala-coxauto** [oracle/oci-ansible-collection#92]
## Issue Report

This is more of an information question.
oci_database_db_home - state present created db home and db as well but state absent does not do both db home and db. 
I have to first delete db using oci_database_database module first and then delete db home. Is this expected behavior or am I missing something ? 

A clear and concise description of what the issue is.

**Expected behavior**

**Environment**

* OS version:

* Ansible version:

    insert output of `ansible --version` here

* OCI Python SDK version:

    insert output of `python -c "import oci;print(oci.__version__)"` here

* OCI Ansible Modules version:

    insert output of (for oracle.oci):
`ansible-galaxy collection list`

**Ansible playbook to reproduce the issue**

    insert a sample playbook to reproduce the issue here(if relevant to the issue)

**Comment by rohnigam** [comment]
hi @mayanala-coxauto ,

You aren't missing anything.

This is the expected behavior.

Thanks.

**Comment by rohnigam** [comment]
Closing this issue. Please feel free to reopen if any other queries.
