### ISSUE TITLE
How to Clone VM Db system using OCI Ansible Collection Module

### ISSUE THREAD

**Issue by vburamdo** [oracle/oci-ansible-collection#94]
Hello Team,

In Console, we have option to clone VM DB system, how we can achieve this via Ansible Collection Module, can you please help me on this and if possible can you please provide sample snippet of the code on the same.

Thanks in Advance.

Regards, Vinod

**Comment by rohnigam** [comment]
hi @vburamdo ,

You can check this module
https://oci-ansible-collection.readthedocs.io/en/latest/collections/oracle/oci/oci_database_db_system_module.html

Check the ```source_db_system_id``` and other relevant params for your purpose.

**Comment by rohnigam** [comment]
Closing this issue. Please reopen if you have any other query.

**Comment by vburamdo** [comment]
@rohnigam thank you for the details which helps for me.
